/**
 * The publish panel's text rules, with no React. The metadata itself is
 * generated by the server (SUMTAB-08); these only pick rows out of it.
 */
import type { PublicationSendResponse } from "@/client"
import { telegramWebBaseUrl } from "@/lib/telegram-web"

export const partsLabel = (n: number) => `${n} message${n === 1 ? "" : "s"}`

/** What a send's answer tells the publisher. */
export function publicationToast(result: PublicationSendResponse): {
  kind: "success" | "error"
  text: string
} {
  if (result.status === "success")
    return {
      kind: "success",
      text: `Published ${partsLabel(result.partsTotal)}.`,
    }
  return {
    kind: "error",
    text: `Publishing stopped after ${result.partsSent} of ${partsLabel(result.partsTotal)}: ${result.error}`,
  }
}

export interface MetadataRow {
  /** The generated line, exactly as the server wrote it. */
  line: string
  label: string
  value: string
  sent: boolean
}

/** `🕒 *Time Range:* value` → its label in sentence case and its value. */
function splitRow(line: string): { label: string; value: string } {
  const match = line.match(/\*([^*]+):\*\s*(.*)$/)
  if (!match) return { label: line, value: "" }
  // Sentence case, an acronym kept: "AI Model" reads "AI model".
  const label = match[1]
    .trim()
    .split(" ")
    .map((w, i) => (i === 0 || w === w.toUpperCase() ? w : w.toLowerCase()))
    .join(" ")
  return { label, value: match[2] }
}

/**
 * The generated metadata's rows, each marked sent when the saved text keeps
 * it. `custom` when the saved text is not the heading plus some of the rows,
 * which is somebody's own writing and turns the ticks off.
 */
export function metadataRows(
  generated: string,
  saved: string,
): { heading: string; rows: MetadataRow[]; custom: boolean } {
  const [heading, ...lines] = generated.split("\n")
  const kept = new Set((saved || generated).split("\n"))
  const rows = lines.map((line) => ({
    line,
    ...splitRow(line),
    sent: kept.has(line),
  }))
  const rebuilt = [heading, ...rows.filter((r) => r.sent).map((r) => r.line)]
  return {
    heading,
    rows,
    custom: rebuilt.join("\n") !== (saved || generated),
  }
}

/**
 * The text to save once `row` is ticked or unticked: the heading and the rows
 * still sent. Every row sent is the generated text, saved as empty so it
 * keeps following the server's generator.
 */
export function withRowToggled(
  heading: string,
  rows: MetadataRow[],
  row: MetadataRow,
): string {
  const next = rows.map((r) => (r === row ? { ...r, sent: !r.sent } : r))
  if (next.every((r) => r.sent)) return ""
  return [heading, ...next.filter((r) => r.sent).map((r) => r.line)].join("\n")
}

export type TelegramSegment =
  | { kind: "plain" | "bold" | "italic"; text: string }
  | { kind: "link"; text: string; url: string }

/** The server's entity pattern (`network.py`): `**b**`, `*i*`, `_i_`, a Citation, `[text](url)`. */
const MARKUP =
  /(\*\*(.*?)\*\*)|(\*(.*?)\*)|(_(.*?)_)|(\[([a-zA-Z0-9_]+)\s+#(\d+)\])|(\[(.*?)\]\((.*?)\))/g

function segment(m: RegExpMatchArray): TelegramSegment {
  if (m[1]) return { kind: "bold", text: m[2] }
  if (m[3] || m[5]) return { kind: "italic", text: m[4] ?? m[6] }
  if (m[7])
    return {
      kind: "link",
      text: m[7],
      url: `${telegramWebBaseUrl()}/${m[8]}/${m[9]}`,
    }
  return { kind: "link", text: m[11], url: m[12] }
}

/** A Part's text as Telegram shows it: plain runs and formatted ones. */
export function telegramSegments(text: string): TelegramSegment[] {
  const out: TelegramSegment[] = []
  let last = 0
  for (const m of text.matchAll(MARKUP)) {
    const at = m.index ?? 0
    if (at > last) out.push({ kind: "plain", text: text.slice(last, at) })
    out.push(segment(m))
    last = at + m[0].length
  }
  if (last < text.length) out.push({ kind: "plain", text: text.slice(last) })
  return out
}
