// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BotInfoRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        credentialId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentialid'
        },
        token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token'
        },
        method: {
            type: 'string',
            title: 'Method'
        },
        params: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params'
        }
    },
    type: 'object',
    required: ['method'],
    title: 'BotInfoRequest'
} as const;

export const CancelSyncJobResponseSchema = {
    properties: {
        jobId: {
            type: 'string',
            title: 'Jobid'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['jobId', 'status'],
    title: 'CancelSyncJobResponse'
} as const;

export const ChannelInfoRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        channelName: {
            type: 'string',
            title: 'Channelname'
        }
    },
    type: 'object',
    required: ['channelName'],
    title: 'ChannelInfoRequest'
} as const;

export const ChannelSyncProgressSchema = {
    properties: {
        channelId: {
            type: 'string',
            title: 'Channelid'
        },
        channelName: {
            type: 'string',
            title: 'Channelname'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        postsFetched: {
            type: 'integer',
            title: 'Postsfetched',
            default: 0
        },
        newLatestId: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Newlatestid'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['channelId', 'channelName', 'status'],
    title: 'ChannelSyncProgress'
} as const;

export const ChatMessageSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['role', 'text'],
    title: 'ChatMessage'
} as const;

export const ChatRequestSchema = {
    properties: {
        channels: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Channels',
            default: []
        },
        postsText: {
            type: 'string',
            title: 'Poststext',
            default: ''
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'English'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        temperature: {
            type: 'number',
            title: 'Temperature',
            default: 0.7
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        history: {
            items: {
                '$ref': '#/components/schemas/ChatMessage'
            },
            type: 'array',
            title: 'History',
            default: []
        },
        ragMode: {
            type: 'boolean',
            title: 'Ragmode',
            default: false
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatRequest'
} as const;

export const EmbedRequestSchema = {
    properties: {
        texts: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Texts'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['texts'],
    title: 'EmbedRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PublishRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        credentialId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentialid'
        },
        token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token'
        },
        chatId: {
            type: 'string',
            title: 'Chatid'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        metadataText: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadatatext'
        }
    },
    type: 'object',
    required: ['chatId', 'text'],
    title: 'PublishRequest'
} as const;

export const RagEmbedRequestSchema = {
    properties: {
        limit: {
            type: 'integer',
            title: 'Limit',
            default: 100
        }
    },
    type: 'object',
    title: 'RagEmbedRequest'
} as const;

export const RagSearchRequestSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        channels: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channels'
        },
        startDate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Startdate'
        },
        endDate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enddate'
        },
        limit: {
            type: 'integer',
            title: 'Limit',
            default: 20
        }
    },
    type: 'object',
    required: ['query'],
    title: 'RagSearchRequest'
} as const;

export const ResolveStartTimeRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        channelName: {
            type: 'string',
            title: 'Channelname'
        },
        targetTimeMs: {
            type: 'integer',
            title: 'Targettimems'
        }
    },
    type: 'object',
    required: ['channelName', 'targetTimeMs'],
    title: 'ResolveStartTimeRequest'
} as const;

export const ScrapeRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        knownLatestId: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Knownlatestid'
        },
        knownDisplayName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Knowndisplayname'
        },
        knownPhotoUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Knownphotourl'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'ScrapeRequest'
} as const;

export const StartSyncJobRequestSchema = {
    properties: {
        channelIds: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channelids'
        },
        source: {
            type: 'string',
            title: 'Source',
            default: 'Manual'
        }
    },
    type: 'object',
    title: 'StartSyncJobRequest'
} as const;

export const StartSyncJobResponseSchema = {
    properties: {
        jobId: {
            type: 'string',
            title: 'Jobid'
        }
    },
    type: 'object',
    required: ['jobId'],
    title: 'StartSyncJobResponse'
} as const;

export const SummaryRequestSchema = {
    properties: {
        channels: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Channels'
        },
        postsText: {
            type: 'string',
            title: 'Poststext'
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'English'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        temperature: {
            type: 'number',
            title: 'Temperature',
            default: 0.7
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['channels', 'postsText'],
    title: 'SummaryRequest'
} as const;

export const SyncJobStatusResponseSchema = {
    properties: {
        jobId: {
            type: 'string',
            title: 'Jobid'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        channels: {
            items: {
                '$ref': '#/components/schemas/ChannelSyncProgress'
            },
            type: 'array',
            title: 'Channels'
        },
        createdAt: {
            type: 'integer',
            title: 'Createdat'
        },
        finishedAt: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finishedat'
        }
    },
    type: 'object',
    required: ['jobId', 'status', 'source', 'channels', 'createdAt'],
    title: 'SyncJobStatusResponse'
} as const;

export const TestProxyRequestSchema = {
    properties: {
        proxyUrl: {
            type: 'string',
            title: 'Proxyurl'
        }
    },
    type: 'object',
    required: ['proxyUrl'],
    title: 'TestProxyRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TorNewIdentityRequestSchema = {
    properties: {
        port: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port'
        }
    },
    type: 'object',
    title: 'TorNewIdentityRequest'
} as const;

export const TranslateRequestSchema = {
    properties: {
        posts: {
            items: {
                additionalProperties: {
                    type: 'string'
                },
                type: 'object'
            },
            type: 'array',
            title: 'Posts'
        },
        targetLanguage: {
            type: 'string',
            title: 'Targetlanguage'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['posts', 'targetLanguage'],
    title: 'TranslateRequest'
} as const;

export const UpdateJobRequestSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['enabled'],
    title: 'UpdateJobRequest'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;