// This file is auto-generated by @hey-api/openapi-ts

export const ActiveSyncJobSummarySchema = {
    properties: {
        jobId: {
            type: 'string',
            title: 'Jobid'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        channelCount: {
            type: 'integer',
            title: 'Channelcount'
        },
        runningChannels: {
            type: 'integer',
            title: 'Runningchannels'
        },
        pendingChannels: {
            type: 'integer',
            title: 'Pendingchannels'
        },
        allowedConcurrency: {
            type: 'integer',
            title: 'Allowedconcurrency'
        },
        concurrencyInUse: {
            type: 'integer',
            title: 'Concurrencyinuse'
        },
        effectiveProxyCapacity: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Effectiveproxycapacity'
        }
    },
    type: 'object',
    required: ['jobId', 'status', 'source', 'channelCount', 'runningChannels', 'pendingChannels', 'allowedConcurrency', 'concurrencyInUse'],
    title: 'ActiveSyncJobSummary'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BotInfoRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        credentialId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentialid'
        },
        token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token'
        },
        method: {
            type: 'string',
            title: 'Method'
        },
        params: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params'
        }
    },
    type: 'object',
    required: ['method'],
    title: 'BotInfoRequest'
} as const;

export const BulkReresolveStartIdsRequestSchema = {
    properties: {
        dryRun: {
            type: 'boolean',
            title: 'Dryrun',
            default: false
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        channelIds: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channelids'
        },
        autoFollowOnly: {
            type: 'boolean',
            title: 'Autofollowonly',
            default: false
        }
    },
    type: 'object',
    title: 'BulkReresolveStartIdsRequest'
} as const;

export const BulkResetSyncRequestSchema = {
    properties: {
        confirm: {
            type: 'boolean',
            title: 'Confirm',
            default: false
        },
        channelIds: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channelids'
        },
        autoFollowOnly: {
            type: 'boolean',
            title: 'Autofollowonly',
            default: false
        }
    },
    type: 'object',
    title: 'BulkResetSyncRequest'
} as const;

export const CancelSyncJobResponseSchema = {
    properties: {
        jobId: {
            type: 'string',
            title: 'Jobid'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['jobId', 'status'],
    title: 'CancelSyncJobResponse'
} as const;

export const ChannelInfoRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        channelName: {
            type: 'string',
            title: 'Channelname'
        }
    },
    type: 'object',
    required: ['channelName'],
    title: 'ChannelInfoRequest'
} as const;

export const ChannelSyncProgressSchema = {
    properties: {
        channelId: {
            type: 'string',
            title: 'Channelid'
        },
        channelName: {
            type: 'string',
            title: 'Channelname'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        postsFetched: {
            type: 'integer',
            title: 'Postsfetched',
            default: 0
        },
        newLatestId: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Newlatestid'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['channelId', 'channelName', 'status'],
    title: 'ChannelSyncProgress'
} as const;

export const ChatMessageSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['role', 'text'],
    title: 'ChatMessage'
} as const;

export const ChatRequestSchema = {
    properties: {
        channels: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Channels',
            default: []
        },
        postsText: {
            type: 'string',
            title: 'Poststext',
            default: ''
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'English'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        temperature: {
            type: 'number',
            title: 'Temperature',
            default: 0.7
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        history: {
            items: {
                '$ref': '#/components/schemas/ChatMessage'
            },
            type: 'array',
            title: 'History',
            default: []
        },
        ragMode: {
            type: 'boolean',
            title: 'Ragmode',
            default: false
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatRequest'
} as const;

export const EmbedRequestSchema = {
    properties: {
        texts: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Texts'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['texts'],
    title: 'EmbedRequest'
} as const;

export const GlobalStartTimeSnapshotSchema = {
    properties: {
        mode: {
            type: 'string',
            title: 'Mode'
        },
        value: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        },
        effectiveMs: {
            type: 'integer',
            title: 'Effectivems'
        }
    },
    type: 'object',
    required: ['mode', 'effectiveMs'],
    title: 'GlobalStartTimeSnapshot'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const JobIntervalsSchema = {
    properties: {
        autoSyncCheckSeconds: {
            type: 'integer',
            title: 'Autosynccheckseconds'
        },
        embeddingsSeconds: {
            type: 'integer',
            title: 'Embeddingsseconds'
        },
        autoSummarySeconds: {
            type: 'integer',
            title: 'Autosummaryseconds'
        },
        retentionHours: {
            type: 'integer',
            title: 'Retentionhours'
        },
        translationBatchSeconds: {
            type: 'integer',
            title: 'Translationbatchseconds'
        }
    },
    type: 'object',
    required: ['autoSyncCheckSeconds', 'embeddingsSeconds', 'autoSummarySeconds', 'retentionHours', 'translationBatchSeconds'],
    title: 'JobIntervals'
} as const;

export const JobsRuntimeSettingsSchema = {
    properties: {
        enabled: {
            additionalProperties: {
                type: 'boolean'
            },
            type: 'object',
            title: 'Enabled'
        },
        intervals: {
            '$ref': '#/components/schemas/JobIntervals'
        }
    },
    type: 'object',
    required: ['enabled', 'intervals'],
    title: 'JobsRuntimeSettings'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NetworkRuntimeSettingsSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxyUrls: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Proxyurls'
        },
        proxyDefaultConcurrency: {
            type: 'integer',
            title: 'Proxydefaultconcurrency',
            default: 1
        },
        proxyConcurrencyOverrides: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Proxyconcurrencyoverrides'
        },
        effectiveProxyCapacity: {
            type: 'integer',
            title: 'Effectiveproxycapacity',
            default: 0
        },
        proxyLanes: {
            items: {
                '$ref': '#/components/schemas/ProxyLaneSnapshot'
            },
            type: 'array',
            title: 'Proxylanes'
        },
        torEnabled: {
            type: 'boolean',
            title: 'Torenabled',
            default: false
        },
        torMode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tormode'
        },
        torProxyUrls: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Torproxyurls'
        },
        torRotationStrategy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Torrotationstrategy'
        },
        torControlEnabled: {
            type: 'boolean',
            title: 'Torcontrolenabled',
            default: false
        },
        torControlPort: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Torcontrolport'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold'
        },
        envFallbackConfigured: {
            type: 'boolean',
            title: 'Envfallbackconfigured'
        },
        usingEnvFallback: {
            type: 'boolean',
            title: 'Usingenvfallback'
        },
        torAvailable: {
            type: 'boolean',
            title: 'Toravailable'
        },
        torSocksProxy: {
            type: 'string',
            title: 'Torsocksproxy'
        },
        effectiveTorEnabled: {
            type: 'boolean',
            title: 'Effectivetorenabled'
        },
        resolvedProxyCount: {
            type: 'integer',
            title: 'Resolvedproxycount'
        },
        resolvedProxies: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Resolvedproxies'
        },
        fetchTimeoutSeconds: {
            type: 'number',
            title: 'Fetchtimeoutseconds'
        },
        fetchRetries: {
            type: 'integer',
            title: 'Fetchretries'
        },
        fetchInitialDelayMs: {
            type: 'integer',
            title: 'Fetchinitialdelayms'
        },
        proxyCooldownMs: {
            type: 'integer',
            title: 'Proxycooldownms'
        },
        telegramApiRetries: {
            type: 'integer',
            title: 'Telegramapiretries'
        },
        telegramApiInitialDelayMs: {
            type: 'integer',
            title: 'Telegramapiinitialdelayms'
        }
    },
    type: 'object',
    required: ['torRotationThreshold', 'envFallbackConfigured', 'usingEnvFallback', 'torAvailable', 'torSocksProxy', 'effectiveTorEnabled', 'resolvedProxyCount', 'fetchTimeoutSeconds', 'fetchRetries', 'fetchInitialDelayMs', 'proxyCooldownMs', 'telegramApiRetries', 'telegramApiInitialDelayMs'],
    title: 'NetworkRuntimeSettings'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const ProxyLaneSnapshotSchema = {
    properties: {
        proxyUrl: {
            type: 'string',
            title: 'Proxyurl'
        },
        maxParallel: {
            type: 'integer',
            title: 'Maxparallel'
        },
        inUse: {
            type: 'integer',
            title: 'Inuse'
        },
        inCooldown: {
            type: 'boolean',
            title: 'Incooldown'
        }
    },
    type: 'object',
    required: ['proxyUrl', 'maxParallel', 'inUse', 'inCooldown'],
    title: 'ProxyLaneSnapshot'
} as const;

export const PublishRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        credentialId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentialid'
        },
        token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token'
        },
        chatId: {
            type: 'string',
            title: 'Chatid'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        metadataText: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadatatext'
        }
    },
    type: 'object',
    required: ['chatId', 'text'],
    title: 'PublishRequest'
} as const;

export const RagEmbedRequestSchema = {
    properties: {
        limit: {
            type: 'integer',
            title: 'Limit',
            default: 100
        }
    },
    type: 'object',
    title: 'RagEmbedRequest'
} as const;

export const RagSearchRequestSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        channels: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channels'
        },
        startDate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Startdate'
        },
        endDate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enddate'
        },
        limit: {
            type: 'integer',
            title: 'Limit',
            default: 20
        },
        scanLimit: {
            type: 'integer',
            title: 'Scanlimit',
            default: 5000
        }
    },
    type: 'object',
    required: ['query'],
    title: 'RagSearchRequest'
} as const;

export const ResolveStartTimeRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        channelName: {
            type: 'string',
            title: 'Channelname'
        },
        targetTimeMs: {
            type: 'integer',
            title: 'Targettimems'
        }
    },
    type: 'object',
    required: ['channelName', 'targetTimeMs'],
    title: 'ResolveStartTimeRequest'
} as const;

export const RetentionRuntimeSettingsSchema = {
    properties: {
        postRetentionDays: {
            type: 'integer',
            title: 'Postretentiondays'
        },
        logRetentionDays: {
            type: 'integer',
            title: 'Logretentiondays'
        }
    },
    type: 'object',
    required: ['postRetentionDays', 'logRetentionDays'],
    title: 'RetentionRuntimeSettings'
} as const;

export const RuntimeConfigResponseSchema = {
    properties: {
        nowMs: {
            type: 'integer',
            title: 'Nowms'
        },
        scrapeCutoffMs: {
            type: 'integer',
            title: 'Scrapecutoffms'
        },
        effectiveGlobalStartTimeMs: {
            type: 'integer',
            title: 'Effectiveglobalstarttimems'
        },
        globalStartTime: {
            '$ref': '#/components/schemas/GlobalStartTimeSnapshot'
        },
        sync: {
            '$ref': '#/components/schemas/SyncRuntimeSettings'
        },
        scraper: {
            '$ref': '#/components/schemas/ScraperRuntimeSettings'
        },
        network: {
            '$ref': '#/components/schemas/NetworkRuntimeSettings'
        },
        jobs: {
            '$ref': '#/components/schemas/JobsRuntimeSettings'
        },
        retention: {
            '$ref': '#/components/schemas/RetentionRuntimeSettings'
        },
        constants: {
            '$ref': '#/components/schemas/RuntimeConstants'
        },
        activeSyncJob: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ActiveSyncJobSummary'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['nowMs', 'scrapeCutoffMs', 'effectiveGlobalStartTimeMs', 'globalStartTime', 'sync', 'scraper', 'network', 'jobs', 'retention', 'constants'],
    title: 'RuntimeConfigResponse'
} as const;

export const RuntimeConstantsSchema = {
    properties: {
        syncMaxRetries: {
            type: 'integer',
            title: 'Syncmaxretries'
        },
        syncRetryBackoffBaseMs: {
            type: 'integer',
            title: 'Syncretrybackoffbasems'
        },
        syncJobSseThrottleMs: {
            type: 'integer',
            title: 'Syncjobssethrottlems'
        },
        syncJobPersistIntervalMs: {
            type: 'integer',
            title: 'Syncjobpersistintervalms'
        },
        autoSyncPauseDurationMs: {
            type: 'integer',
            title: 'Autosyncpausedurationms'
        },
        autoSyncFailureThresholdMin: {
            type: 'integer',
            title: 'Autosyncfailurethresholdmin'
        },
        embeddingsChunkSize: {
            type: 'integer',
            title: 'Embeddingschunksize'
        },
        embeddingsBackfillLimitDefault: {
            type: 'integer',
            title: 'Embeddingsbackfilllimitdefault'
        },
        translationBatchLimit: {
            type: 'integer',
            title: 'Translationbatchlimit'
        },
        translationBatchMaxChars: {
            type: 'integer',
            title: 'Translationbatchmaxchars'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        }
    },
    type: 'object',
    required: ['syncMaxRetries', 'syncRetryBackoffBaseMs', 'syncJobSseThrottleMs', 'syncJobPersistIntervalMs', 'autoSyncPauseDurationMs', 'autoSyncFailureThresholdMin', 'embeddingsChunkSize', 'embeddingsBackfillLimitDefault', 'translationBatchLimit', 'translationBatchMaxChars', 'environment'],
    title: 'RuntimeConstants'
} as const;

export const ScrapeRequestSchema = {
    properties: {
        proxyEnabled: {
            type: 'boolean',
            title: 'Proxyenabled',
            default: false
        },
        proxies: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxies'
        },
        torAutoRotate: {
            type: 'boolean',
            title: 'Torautorotate',
            default: false
        },
        torRotationThreshold: {
            type: 'integer',
            title: 'Torrotationthreshold',
            default: 10
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        knownLatestId: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Knownlatestid'
        },
        knownDisplayName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Knowndisplayname'
        },
        knownPhotoUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Knownphotourl'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'ScrapeRequest'
} as const;

export const ScraperRuntimeSettingsSchema = {
    properties: {
        maxPostsPerChannel: {
            type: 'integer',
            title: 'Maxpostsperchannel'
        },
        iterationLimit: {
            type: 'integer',
            title: 'Iterationlimit'
        }
    },
    type: 'object',
    required: ['maxPostsPerChannel', 'iterationLimit'],
    title: 'ScraperRuntimeSettings'
} as const;

export const StartSyncJobRequestSchema = {
    properties: {
        channelIds: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channelids'
        },
        source: {
            type: 'string',
            title: 'Source',
            default: 'Manual'
        }
    },
    type: 'object',
    title: 'StartSyncJobRequest'
} as const;

export const StartSyncJobResponseSchema = {
    properties: {
        jobId: {
            type: 'string',
            title: 'Jobid'
        }
    },
    type: 'object',
    required: ['jobId'],
    title: 'StartSyncJobResponse'
} as const;

export const SummaryRequestSchema = {
    properties: {
        channels: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Channels'
        },
        postsText: {
            type: 'string',
            title: 'Poststext'
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'English'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        temperature: {
            type: 'number',
            title: 'Temperature',
            default: 0.7
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['channels', 'postsText'],
    title: 'SummaryRequest'
} as const;

export const SyncJobStatusResponseSchema = {
    properties: {
        jobId: {
            type: 'string',
            title: 'Jobid'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        channels: {
            items: {
                '$ref': '#/components/schemas/ChannelSyncProgress'
            },
            type: 'array',
            title: 'Channels'
        },
        createdAt: {
            type: 'integer',
            title: 'Createdat'
        },
        finishedAt: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finishedat'
        }
    },
    type: 'object',
    required: ['jobId', 'status', 'source', 'channels', 'createdAt'],
    title: 'SyncJobStatusResponse'
} as const;

export const SyncRuntimeSettingsSchema = {
    properties: {
        autoSyncEnabled: {
            type: 'boolean',
            title: 'Autosyncenabled'
        },
        autoSyncInterval: {
            type: 'integer',
            title: 'Autosyncinterval'
        },
        syncConcurrency: {
            type: 'integer',
            title: 'Syncconcurrency'
        },
        consecutiveFailures: {
            type: 'integer',
            title: 'Consecutivefailures'
        },
        autoSyncPauseUntil: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Autosyncpauseuntil'
        },
        globalStartTimeMode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Globalstarttimemode'
        },
        globalStartTimeValue: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Globalstarttimevalue'
        }
    },
    type: 'object',
    required: ['autoSyncEnabled', 'autoSyncInterval', 'syncConcurrency', 'consecutiveFailures'],
    title: 'SyncRuntimeSettings'
} as const;

export const TestProxyRequestSchema = {
    properties: {
        proxyUrl: {
            type: 'string',
            title: 'Proxyurl'
        }
    },
    type: 'object',
    required: ['proxyUrl'],
    title: 'TestProxyRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TorNewIdentityRequestSchema = {
    properties: {
        port: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port'
        }
    },
    type: 'object',
    title: 'TorNewIdentityRequest'
} as const;

export const TranslateRequestSchema = {
    properties: {
        posts: {
            items: {
                additionalProperties: {
                    type: 'string'
                },
                type: 'object'
            },
            type: 'array',
            title: 'Posts'
        },
        targetLanguage: {
            type: 'string',
            title: 'Targetlanguage'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        provider: {
            type: 'string',
            title: 'Provider',
            default: 'gemini'
        }
    },
    type: 'object',
    required: ['posts', 'targetLanguage'],
    title: 'TranslateRequest'
} as const;

export const UpdateJobRequestSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['enabled'],
    title: 'UpdateJobRequest'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;