// This file is auto-generated by @hey-api/openapi-ts

export type ActiveSyncJobSummary = {
    jobId: string;
    status: string;
    source: string;
    channelCount: number;
    runningChannels: number;
    pendingChannels: number;
    allowedConcurrency: number;
    concurrencyInUse: number;
    effectiveProxyCapacity?: (number | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BotInfoRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    credentialId?: (string | null);
    token?: (string | null);
    method: string;
    params?: ({
    [key: string]: unknown;
} | null);
};

export type BulkChannelSettingGroupRequest = {
    channelIds: Array<(string)>;
    settingGroupId: string;
};

export type BulkChannelTagsRequest = {
    updates: Array<BulkChannelTagUpdate>;
};

/**
 * Result of ``PATCH /data/channels/bulk-tags``.
 *
 * Returns the rewritten channel rows so the client can refresh without a
 * second round-trip.
 */
export type BulkChannelTagsResponse = {
    updated?: number;
    channels?: Array<ChannelResponse>;
};

export type BulkChannelTagUpdate = {
    channelId: string;
    tags: Array<{
        [key: string]: unknown;
    }>;
};

export type BulkFollowChannelEntry = {
    name: string;
    discoveredVia?: (DiscoveredViaPayload | null);
};

export type BulkFollowJobStatusResponse = {
    followJobId: string;
    status: string;
    source: string;
    total: number;
    completed: number;
    added: number;
    skipped: number;
    unavailable: number;
    failed: number;
    results: Array<FollowChannelResultResponse>;
    syncJobId?: (string | null);
    createdAt: number;
    finishedAt?: (number | null);
};

export type BulkFollowRequest = {
    channels: Array<BulkFollowChannelEntry>;
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
};

export type BulkFollowStartResponse = {
    followJobId: string;
};

export type BulkReresolveStartIdsRequest = {
    dryRun?: boolean;
    limit?: (number | null);
    channelIds?: (Array<(string)> | null);
    autoFollowOnly?: boolean;
};

/**
 * Result of ``POST /data/channels/bulk-reresolve-start-ids``.
 *
 * Mirrors `BulkReresolveResult`. The operation is deprecated — `start_id` no
 * longer drives sync — hence the always-true `deprecated` flag and `message`.
 */
export type BulkReresolveStartIdsResponse = {
    updated?: number;
    skipped?: number;
    wouldUpdate?: number;
    errors?: Array<{
        [key: string]: (string);
    }>;
    deprecated?: boolean;
    message?: string;
};

export type BulkResetSyncRequest = {
    confirm?: boolean;
    channelIds?: (Array<(string)> | null);
    autoFollowOnly?: boolean;
};

/**
 * Result of ``POST /data/channels/bulk-reset-sync``. Mirrors `BulkResetSyncResult`.
 */
export type BulkResetSyncResponse = {
    channelsReset?: number;
    postsDeleted?: number;
    jobId?: (string | null);
    errors?: Array<{
        [key: string]: (string);
    }>;
};

/**
 * Result of ``PATCH /data/channels/bulk-setting-group``.
 */
export type BulkSettingGroupResponse = {
    updated?: number;
    settingGroupId: string;
};

export type BulkSyncSettingsRequest = {
    channelIds?: (Array<(string)> | null);
    regularSyncEnabled?: (boolean | null);
    dynamicSyncEnabled?: (boolean | null);
    autoSyncIntervalMinutes?: (number | null);
    dynamicSyncExpectedPosts?: (number | null);
};

/**
 * A bulk write that only reports how many rows it touched.
 */
export type BulkUpdatedResponse = {
    updated?: number;
};

/**
 * Result of ``POST /data/posts/bulk``.
 */
export type BulkUpsertPostsResponse = {
    upserted?: number;
};

export type CancelBulkFollowResponse = {
    followJobId: string;
    status: string;
};

export type CancelSyncJobResponse = {
    jobId: string;
    status: string;
};

/**
 * Pointer to the most recent post that referenced a candidate.
 *
 * A pointer rather than the post body on purpose: retention may prune the post
 * later, and callers render a Telegram web-view link from these three fields so
 * the evidence stays reachable outside our corpus.
 */
export type CandidateSamplePostResponse = {
    channelName: string;
    postId: number;
    timestamp: number;
};

/**
 * One carrier channel's contribution to a candidate's totals.
 */
export type CandidateSeenInResponse = {
    channelName: string;
    counts: SignalCountsResponse;
    total: number;
};

export type ChannelInfoRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    channelName: string;
};

/**
 * One channel, as `channel_to_camel` builds it.
 *
 * Carries the inherited setting-group fields and the optional ``stats`` block
 * through ``extra`` — see the module docstring for why they are not declared.
 */
export type ChannelResponse = {
    id: string;
    name: string;
    displayName?: (string | null);
    photoUrl?: (string | null);
    bio?: (string | null);
    subscribers?: (string | null);
    photos?: (string | null);
    videos?: (string | null);
    files?: (string | null);
    links?: (string | null);
    startId?: (number | null);
    startTime?: (number | null);
    tags?: Array<unknown>;
    lastUpdated?: (number | null);
    nextRegularSyncAt?: (number | null);
    nextDynamicSyncAt?: (number | null);
    language?: (string | null);
    followedAt?: (number | null);
    telegramChatId?: (number | null);
    discoveredVia?: ({
    [key: string]: unknown;
} | null);
    historyCompleteToCutoff?: boolean;
    historyReachedChannelStart?: boolean;
    anchorPostId?: (number | null);
    oldestStoredPostTimestamp?: (number | null);
    [key: string]: unknown | string | boolean;
};

/**
 * Post aggregates for one channel, as `compute_channel_stats` builds it.
 */
export type ChannelStatsResponse = {
    count: number;
    minId?: (number | null);
    maxId?: (number | null);
    velocity?: number;
};

export type ChannelSyncProgress = {
    channelId: string;
    channelName: string;
    status: string;
    postsFetched?: number;
    newLatestId?: (number | null);
    error?: (string | null);
};

/**
 * Body for ``PUT /data/channels/{id}``.
 *
 * Deliberately permissive, like `SummaryUpsertRequest`. `upsert_channel`
 * normalises camelCase to snake_case itself, rejects server-managed and
 * group-inherited fields with a 400, and writes only recognised
 * `Channel.model_fields` — so validation belongs there, not here, and a
 * stricter model would turn those 400s into 422s and change the API's error
 * contract.
 */
export type ChannelUpsertRequest = {
    name?: (string | null);
    displayName?: (string | null);
    photoUrl?: (string | null);
    bio?: (string | null);
    subscribers?: (string | null);
    startId?: (number | null);
    startTime?: (number | null);
    tags?: (Array<unknown> | null);
    language?: (string | null);
    followedAt?: (number | null);
    telegramChatId?: (number | null);
    discoveredVia?: ({
    [key: string]: unknown;
} | null);
    [key: string]: unknown;
};

export type ChatMessage = {
    role: string;
    text: string;
};

export type ChatRequest = {
    channels?: Array<(string)>;
    channelsText?: string;
    postsText?: string;
    scope?: (PromptScopeInput | null);
    language?: string;
    model?: (string | null);
    temperature?: number;
    message: string;
    history?: Array<ChatMessage>;
    ragMode?: boolean;
    provider?: string;
};

/**
 * How many rows `DELETE /data/tables/{name}` removed.
 */
export type ClearTableResponse = {
    deleted?: number;
};

/**
 * Row counts across the corpus, scoped to the operator.
 *
 * `embeddedPostCount` is deliberately **not** operator-scoped: embeddings are a
 * corpus-level artefact shared across users (see the multi-user seam note in
 * the plan), so it counts the whole table while the rest count the operator's
 * rows.
 */
export type DbStatsResponse = {
    postCount?: number;
    channelCount?: number;
    summaryCount?: number;
    embeddedPostCount?: number;
    botCount?: number;
    destinationCount?: number;
    publishLogCount?: number;
    syncLogCount?: number;
    llmLogCount?: number;
    embeddingLogCount?: number;
    networkLogCount?: number;
};

/**
 * One discovered handle, as `_to_candidate` builds it.
 *
 * `isFollowed` / `isIgnored` are resolved against live state, never frozen —
 * counts are historical, follow state is not.
 */
export type DiscoverCandidateResponse = {
    name: string;
    displayName?: (string | null);
    counts: SignalCountsResponse;
    total?: number;
    seenIn?: Array<CandidateSeenInResponse>;
    seenInCount?: number;
    lastSeen?: number;
    isFollowed?: boolean;
    isIgnored?: boolean;
    samplePost: CandidateSamplePostResponse;
};

/**
 * `PostScopeRequest` plus the signal-kind filter and the cap/scope inputs.
 *
 * `channelNames` is re-declared as required: the discovery aggregate is always
 * asked about an explicit selection, and the query-string version required it
 * too.
 *
 * `maxPerChannelMode`/`seed` and `postIds` are what let Discover reproduce the
 * two scopes that used to fall back to a second, client-side implementation of
 * the same counting rules — the `random` cap and a semantic query
 * (IDEA-011 D14).
 */
export type DiscoverCandidatesRequest = {
    channelNames: Array<(string)>;
    startDate?: (number | null);
    endDate?: (number | null);
    keyword?: (string | null);
    forwarded?: string;
    media?: string;
    maxPerChannel?: number;
    signals?: (Array<(string)> | null);
    maxPerChannelMode?: string;
    seed?: number;
    postIds?: (Array<DiscoverPostRef> | null);
};

/**
 * Result of the stateless aggregation, `POST /discover/candidates`.
 */
export type DiscoverCandidatesResponse = {
    candidates?: Array<DiscoverCandidateResponse>;
    scopeCounts: ScopeCountsResponse;
    postsInScope?: number;
};

export type DiscoveredViaPayload = {
    channelName: string;
    postId: number;
    timestamp: number;
};

/**
 * Handles newly dismissed. Excludes ones already dismissed: the call is
 * idempotent, so a re-dismissal is a no-op rather than an error.
 */
export type DiscoverIgnoredAddedResponse = {
    ignored?: Array<(string)>;
};

/**
 * Handles whose dismissal was undone. Unknown handles are omitted.
 */
export type DiscoverIgnoredRemovedResponse = {
    removed?: Array<(string)>;
};

/**
 * Handles to dismiss, or to un-dismiss.
 *
 * A list rather than a path parameter so a batch can be toggled in one call —
 * which is why the DELETE carries a body too.
 */
export type DiscoverIgnoreRequest = {
    handles: Array<(string)>;
    reason?: (string | null);
};

export type DiscoverPostRef = {
    channelName: string;
    postId: number;
};

/**
 * Probe queue state, for the progress display.
 *
 * `queued` and `retrying` are split because they behave differently on screen:
 * `queued` drains to zero and can drive a progress bar, while `retrying` may
 * never reach zero — a permanently unreachable handle keeps retrying at the
 * backoff ceiling forever, by design.
 */
export type DiscoverProbeQueueResponse = {
    queued?: number;
    retrying?: number;
    resolved?: number;
    unavailable?: number;
    enabled?: boolean;
    running?: boolean;
};

/**
 * The handles now queued for a fresh probe.
 *
 * Includes handles that had never been probed: the UI offers recheck on rows
 * whose verdict has not arrived yet, so asking for one nobody has looked at is
 * reasonable rather than an error. A list, not a count — the caller needs to
 * know *which* rows to repaint as pending.
 */
export type DiscoverProbeRecheckResponse = {
    requeued?: Array<(string)>;
};

/**
 * Handles whose cached verdict should be discarded and re-queued.
 */
export type DiscoverProbeRequest = {
    handles: Array<(string)>;
};

/**
 * A saved report without its candidate rows, as the history list ships it.
 *
 * `candidates` is the corpus-sized field — a wide-scope report holds the full
 * single-reference tail — so the list carries `candidateCount` instead.
 */
export type DiscoverReportListItemResponse = {
    id: string;
    scope: DiscoverReportScopeResponse;
    scopeCounts: ScopeCountsResponse;
    postsInScope?: number;
    timestamp?: number;
    candidateCount?: number;
};

/**
 * A saved report with every candidate and its live follow/probe state.
 */
export type DiscoverReportResponse = {
    id: string;
    scope: DiscoverReportScopeResponse;
    scopeCounts: ScopeCountsResponse;
    postsInScope?: number;
    timestamp?: number;
    candidateCount?: number;
    candidates?: Array<ReportCandidateResponse>;
};

/**
 * The frozen inputs a report was generated for.
 *
 * Rendered by the scope card instead of live selection state — after the user
 * changes tabs, live state no longer describes where the numbers came from.
 */
export type DiscoverReportScopeResponse = {
    channels?: Array<(string)>;
    startDate?: number;
    endDate?: number;
    signals?: Array<(string)>;
    keyword?: (string | null);
    forwarded?: string;
    media?: string;
    maxPerChannel?: number;
    maxPerChannelMode?: string;
    seed?: number;
    scopedPostCount?: (number | null);
};

/**
 * One embedding batch.
 */
export type EmbeddingLogResponse = {
    id: string;
    textCount?: number;
    tokensEstimated?: (number | null);
    duration?: number;
    status: string;
    error?: (string | null);
    timestamp?: number;
};

export type EmbedRequest = {
    texts: Array<(string)>;
    model?: (string | null);
    provider?: string;
};

export type FollowChannelResultResponse = {
    name: string;
    status: 'pending' | 'running' | 'added' | 'unavailable' | 'skipped' | 'error' | 'cancelled';
    reason?: (string | null);
    error?: (string | null);
};

export type status = 'pending' | 'running' | 'added' | 'unavailable' | 'skipped' | 'error' | 'cancelled';

export type GlobalStartTimeSnapshot = {
    mode: string;
    value?: (string | number | null);
    effectiveMs: number;
};

/**
 * A cached verdict about one handle, as `probe_to_camel` builds it.
 *
 * `status` is the structural fact (`ok` | `unavailable` | `unknown`); `kind`
 * (`channel` | `group` | `bot` | `user` | `unknown`) is an HTML heuristic that
 * sharpens the wording and is never filtered on.
 */
export type HandleProbeResponse = {
    handle: string;
    status?: string;
    kind?: string;
    displayName?: (string | null);
    bio?: (string | null);
    subscribers?: (string | null);
    photoUrl?: (string | null);
    attempts?: number;
    lastError?: (string | null);
    checkedAt?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * One dismissed candidate.
 */
export type IgnoredChannelResponse = {
    handle: string;
    reason?: (string | null);
    createdAt?: number;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobIntervals = {
    autoSyncCheckSeconds: number;
    embeddingsSeconds: number;
    autoSummarySeconds: number;
    retentionHours: number;
    translationBatchSeconds: number;
};

export type JobsRuntimeSettings = {
    enabled: {
        [key: string]: (boolean);
    };
    intervals: JobIntervals;
};

/**
 * One model call: the prompt, the response, and what it cost.
 *
 * `protected_namespaces=()` is required, not decorative. Pydantic v2 reserves
 * the `model_` prefix for its own API, and this table has both a `model` column
 * and a `model_config_json` one — the latter collides with `BaseModel.model_config`
 * itself. Without the override, declaring these fields raises at class-creation
 * time. Renaming the columns is not an option: they are the wire format.
 */
export type LLMLogResponse = {
    id: string;
    model: string;
    prompt: string;
    response: string;
    systemInstruction?: (string | null);
    modelConfig?: ({
    [key: string]: unknown;
} | null);
    fullRequest?: LogPayload;
    fullResponse?: LogPayload;
    tokens?: (number | null);
    duration?: (number | null);
    status: string;
    error?: (string | null);
    timestamp?: number;
    type?: string;
};

export type LogPayload = {
    [key: string]: unknown;
} | Array<unknown> | null;

/**
 * Result of a bulk log write: how many rows were accepted.
 */
export type LogWriteResponse = {
    upserted?: number;
};

export type Message = {
    message: string;
};

/**
 * One outbound HTTP fetch, including which proxy lane carried it.
 */
export type NetworkLogResponse = {
    id: string;
    url: string;
    method: string;
    status: string;
    statusCode?: (number | null);
    error?: (string | null);
    duration?: number;
    timestamp?: number;
    source?: string;
    proxyUsed?: (string | null);
    attempts?: (number | null);
    telemetry?: ({
    [key: string]: unknown;
} | null);
};

export type NetworkRuntimeSettings = {
    proxyEnabled?: boolean;
    proxyUrls?: Array<(string)>;
    proxyDefaultConcurrency?: number;
    proxyConcurrencyOverrides?: {
        [key: string]: (number);
    };
    effectiveProxyCapacity?: number;
    proxyLanes?: Array<ProxyLaneSnapshot>;
    torEnabled?: boolean;
    torMode?: (string | null);
    torProxyUrls?: (string | null);
    torRotationStrategy?: (string | null);
    torControlEnabled?: boolean;
    torControlPort?: (number | null);
    torAutoRotate?: boolean;
    torRotationThreshold: number;
    envFallbackConfigured: boolean;
    usingEnvFallback: boolean;
    torAvailable: boolean;
    torSocksProxy: string;
    effectiveTorEnabled: boolean;
    resolvedProxyCount: number;
    resolvedProxies?: Array<(string)>;
    fetchTimeoutSeconds: number;
    fetchRetries: number;
    fetchInitialDelayMs: number;
    proxyCooldownMs: number;
    telegramApiRetries: number;
    telegramApiInitialDelayMs: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * `PostScopeRequest` plus the feed's paging, cap mode and sort.
 *
 * `limit`/`offset` keep the same bounds the query params enforced, so an
 * out-of-range page is still a 422 rather than an unbounded read.
 */
export type PostFeedRequest = {
    channelNames?: (Array<(string)> | null);
    startDate?: (number | null);
    endDate?: (number | null);
    keyword?: (string | null);
    forwarded?: string;
    media?: string;
    maxPerChannel?: number;
    channelName?: (string | null);
    limit?: number;
    offset?: number;
    maxPerChannelMode?: string;
    sort?: string;
    seed?: number;
};

export type PostLookupRef = {
    channelName: string;
    postId: number;
};

/**
 * Batch of `(channelName, postId)` refs to resolve.
 *
 * Capped so this cannot become another way to ask for unbounded rows.
 */
export type PostLookupRequest = {
    posts: Array<PostLookupRef>;
};

/**
 * One post, as `post_to_camel` builds it.
 */
export type PostResponse = {
    id: number;
    channelName: string;
    text?: string;
    date?: string;
    timestamp?: number;
    forwardedFrom?: (string | null);
    forwardedFromName?: (string | null);
    isAnchor?: boolean;
    retrievedAt?: (number | null);
    retrievalJobId?: (string | null);
    retrievalPass?: (string | null);
    retrievalSource?: (string | null);
    media?: ({
    [key: string]: unknown;
} | null);
    links?: (Array<unknown> | null);
    replyToPostId?: (number | null);
    replyTo?: ({
    [key: string]: unknown;
} | null);
};

/**
 * A post scope carried in a request body rather than a query string.
 *
 * The channel selection can run to the full account — over a thousand handles —
 * which as `?channelNames=a,b,c,...` produced URLs long enough to hit proxy and
 * server header limits. A body has no such ceiling.
 */
export type PostScopeRequest = {
    channelNames?: (Array<(string)> | null);
    startDate?: (number | null);
    endDate?: (number | null);
    keyword?: (string | null);
    forwarded?: string;
    media?: string;
    maxPerChannel?: number;
};

/**
 * A Posts-feed scope the backend resolves into the prompt's posts block,
 * instead of the client shipping a pre-built ``postsText``. Mirrors the
 * frontend feed query params.
 */
export type PromptScopeInput = {
    startDate?: (number | null);
    endDate?: (number | null);
    keyword?: (string | null);
    forwarded?: string;
    media?: string;
    maxPerChannel?: number;
    maxPerChannelMode?: string;
    sort?: string;
    seed?: number;
};

export type ProxyLaneSnapshot = {
    proxyUrl: string;
    maxParallel: number;
    inUse: number;
    inCooldown: boolean;
};

/**
 * One attempt to publish a summary to a Telegram chat.
 */
export type PublishLogResponse = {
    id: string;
    summaryId: string;
    botId: string;
    botName: string;
    chatId: string;
    chatName: string;
    status: string;
    error?: (string | null);
    timestamp?: number;
    fullRequest?: LogPayload;
    fullResponse?: LogPayload;
    textSent?: (string | null);
};

export type PublishRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    credentialId?: (string | null);
    token?: (string | null);
    chatId: string;
    text: string;
    metadataText?: (string | null);
};

/**
 * Result of `DELETE /data/logs`.
 *
 * Three call shapes share one response. A retention sweep (`olderThanDays`)
 * deletes across every table and reports the per-type breakdown plus a
 * `total`; deleting one entry or clearing one type reports a bare `deleted`
 * count and no breakdown. `deleted` is therefore declared loose — it is an
 * `int` in two of the three cases and a `dict[str, int]` in the third — and
 * `total` is genuinely absent rather than null for the other two, so it stays
 * undeclared and travels through `extra`.
 */
export type PurgeLogsResponse = {
    deleted?: ({
    [key: string]: (number);
} | number);
    [key: string]: unknown;
};

export type RagEmbedRequest = {
    limit?: number;
};

export type RagSearchRequest = {
    query: string;
    channels?: (Array<(string)> | null);
    startDate?: (number | null);
    endDate?: (number | null);
    limit?: number;
    scanLimit?: number;
};

/**
 * A candidate read back from a saved report, with its probe verdict joined.
 *
 * `probe` is `null` for a handle nothing has looked at yet, which callers must
 * render as "not checked" rather than as a verdict: an unprobed handle and one
 * confirmed unfollowable must not look the same.
 */
export type ReportCandidateResponse = {
    name: string;
    displayName?: (string | null);
    counts: SignalCountsResponse;
    total?: number;
    seenIn?: Array<CandidateSeenInResponse>;
    seenInCount?: number;
    lastSeen?: number;
    isFollowed?: boolean;
    isIgnored?: boolean;
    samplePost: CandidateSamplePostResponse;
    probe?: (HandleProbeResponse | null);
};

export type ResolveStartTimeRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    channelName: string;
    targetTimeMs: number;
};

export type RetentionRuntimeSettings = {
    postRetentionDays: number;
    logRetentionDays: number;
    payloadRetentionDays: number;
};

export type RuntimeConfigResponse = {
    nowMs: number;
    scrapeCutoffMs: number;
    effectiveGlobalStartTimeMs: number;
    globalStartTime: GlobalStartTimeSnapshot;
    sync: SyncRuntimeSettings;
    scraper: ScraperRuntimeSettings;
    network: NetworkRuntimeSettings;
    jobs: JobsRuntimeSettings;
    retention: RetentionRuntimeSettings;
    constants: RuntimeConstants;
    activeSyncJob?: (ActiveSyncJobSummary | null);
};

export type RuntimeConstants = {
    syncMaxRetries: number;
    syncRetryBackoffBaseMs: number;
    syncJobSseThrottleMs: number;
    syncJobPersistIntervalMs: number;
    autoSyncPauseDurationMs: number;
    autoSyncFailureThresholdMin: number;
    embeddingsChunkSize: number;
    embeddingsBackfillLimitDefault: number;
    translationBatchLimit: number;
    translationBatchMaxChars: number;
    environment: string;
};

/**
 * How many posts in scope carried each signal kind.
 *
 * Post-level, not reference-level: a post forwarding two channels counts once
 * towards `forwardPosts`, which is what makes these comparable with
 * `postsInScope`.
 */
export type ScopeCountsResponse = {
    forwardPosts?: number;
    mentionPosts?: number;
    linkPosts?: number;
};

export type ScrapeRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    url: string;
    knownLatestId?: (number | null);
    knownDisplayName?: (string | null);
    knownPhotoUrl?: (string | null);
};

export type ScraperRuntimeSettings = {
    maxPostsPerChannel: number;
    iterationLimit: number;
};

export type SettingGroupWriteRequest = {
    name?: (string | null);
    regularSyncEnabled?: (boolean | null);
    dynamicSyncEnabled?: (boolean | null);
    autoSyncIntervalMinutes?: (number | null);
    dynamicSyncExpectedPosts?: (number | null);
    autoFollowForwarded?: (boolean | null);
    isFrozen?: (boolean | null);
    isUnavailableOnWebView?: (boolean | null);
    includeInSyncAll?: (boolean | null);
    includeInBulkSync?: (boolean | null);
    allowIndividualSync?: (boolean | null);
    resetSyncEnabled?: (boolean | null);
};

/**
 * References by signal kind.
 *
 * Always carries all three kinds even when the request enabled a subset, so a
 * caller can render a stable set of columns.
 */
export type SignalCountsResponse = {
    forward?: number;
    mention?: number;
    link?: number;
};

export type StartSyncJobRequest = {
    channelIds?: (Array<(string)> | null);
    source?: string;
    syncMode?: ('sync_all' | 'bulk' | 'individual' | 'recheck_restricted' | null);
};

export type StartSyncJobResponse = {
    jobId: string;
};

/**
 * A bare outcome acknowledgement, e.g. ``{"status": "deleted"}``.
 */
export type StatusResponse = {
    status: string;
};

/**
 * List projection, as `summary_to_camel_light` builds it.
 *
 * Drops the three corpus-sized fields and adds ``chatMessageCount``, which the
 * service always sets. ``promptExcerpt`` is *not* declared: it appears only
 * when the summary actually has prompt text, and declaring it would emit
 * ``"promptExcerpt": null`` for every summary that has none. It still reaches
 * the client through ``extra="allow"``.
 */
export type SummaryListItemResponse = {
    id: string;
    text: string;
    channels?: Array<(string)>;
    startDate?: number;
    endDate?: number;
    language?: string;
    model?: (string | null);
    postCount?: (number | null);
    timestamp?: number;
    chatMessageCount?: number;
    [key: string]: unknown | string | number;
};

export type SummaryRequest = {
    channels: Array<(string)>;
    channelsText?: string;
    postsText?: string;
    scope?: (PromptScopeInput | null);
    language?: string;
    model?: (string | null);
    temperature?: number;
    provider?: string;
};

/**
 * One summary in the full projection, as `summary_to_camel` builds it.
 *
 * Carries every key of ``extra``, including the corpus-sized
 * ``citedPosts`` / ``promptText`` / ``chatMessages``.
 */
export type SummaryResponse = {
    id: string;
    text: string;
    channels?: Array<(string)>;
    startDate?: number;
    endDate?: number;
    language?: string;
    model?: (string | null);
    postCount?: (number | null);
    timestamp?: number;
    [key: string]: unknown | string | number;
};

/**
 * Body for ``PUT /data/summaries/{id}``.
 *
 * Intentionally permissive. The service accepts both camelCase and snake_case
 * for the base columns, routes anything unrecognised into ``extra``, and
 * treats an explicit ``null`` as "remove this key from ``extra``" — behaviour
 * a stricter model would break. Declaring the base fields still documents the
 * shape and gives the generated client something better than ``unknown``.
 */
export type SummaryUpsertRequest = {
    text?: (string | null);
    channels?: (Array<(string)> | null);
    startDate?: (number | null);
    endDate?: (number | null);
    language?: (string | null);
    model?: (string | null);
    postCount?: (number | null);
    timestamp?: (number | null);
    [key: string]: unknown;
};

export type SyncJobStatusResponse = {
    jobId: string;
    status: string;
    source: string;
    channels: Array<ChannelSyncProgress>;
    createdAt: number;
    finishedAt?: (number | null);
};

/**
 * One channel sync attempt, with its payload row folded back in.
 *
 * `fullRequest` / `fullResponse` live in `tg_sync_log_payloads` and are joined
 * on an OUTER join: that table is truncatable, so a log whose payload has been
 * reclaimed still lists and simply reports nulls.
 */
export type SyncLogResponse = {
    id: string;
    channelName: string;
    status: string;
    postsCount?: number;
    newLatestId?: (number | null);
    error?: (string | null);
    timestamp?: number;
    source?: string;
    fullRequest?: LogPayload;
    fullResponse?: LogPayload;
};

/**
 * One resource's sync etag, as `get_sync_meta` builds it.
 */
export type SyncMetaEntry = {
    etag: string;
    updatedAt: string;
};

export type SyncRuntimeSettings = {
    regularSyncIntervalMinutes: number;
    dynamicSyncEnabledDefault: boolean;
    dynamicSyncExpectedPostsDefault: number;
    syncFailureBackoffMinutes: number;
    syncConcurrency: number;
    consecutiveFailures: number;
    autoSyncPauseUntil?: (number | null);
    globalStartTimeMode?: (string | null);
    globalStartTimeValue?: (string | number | null);
};

/**
 * Row count and on-disk footprint for one exportable table.
 *
 * `size` is the whole physical footprint (heap + TOAST + indexes) straight from
 * Postgres, not an estimate: JSON payload columns can dwarf what the row count
 * alone suggests.
 */
export type TableSizeResponse = {
    name: string;
    count?: number;
    size?: number;
};

export type TagRequest = {
    channels: Array<(string)>;
    channelsText?: string;
    postsText?: string;
    scope?: (PromptScopeInput | null);
    allTags?: string;
    tagMode?: string;
    model?: (string | null);
    temperature?: number;
    provider?: string;
    tagsPerChannelMin?: (number | null);
    tagsPerChannelMax?: (number | null);
};

export type TestProxyRequest = {
    proxyUrl: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TorNewIdentityRequest = {
    port?: (number | null);
};

export type TranslateRequest = {
    posts: Array<{
        [key: string]: (string);
    }>;
    targetLanguage: string;
    model?: (string | null);
    provider?: string;
};

export type UpdateJobRequest = {
    enabled: boolean;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AiApiListModelsResponse = ({
    [key: string]: unknown;
});

export type AiApiSummaryData = {
    requestBody: SummaryRequest;
};

export type AiApiSummaryResponse = ({
    [key: string]: unknown;
});

export type AiApiSummaryPromptData = {
    requestBody: SummaryRequest;
};

export type AiApiSummaryPromptResponse = ({
    [key: string]: unknown;
});

export type AiApiSummaryStreamData = {
    requestBody: SummaryRequest;
};

export type AiApiSummaryStreamResponse = (unknown);

export type AiApiChatStreamData = {
    requestBody: ChatRequest;
};

export type AiApiChatStreamResponse = (unknown);

export type AiApiTagPromptData = {
    requestBody: TagRequest;
};

export type AiApiTagPromptResponse = ({
    [key: string]: (string);
});

export type AiApiTagStreamData = {
    requestBody: TagRequest;
};

export type AiApiTagStreamResponse = (unknown);

export type AiApiEmbeddingsData = {
    requestBody: EmbedRequest;
};

export type AiApiEmbeddingsResponse = ({
    [key: string]: unknown;
});

export type AiApiTranslateData = {
    requestBody: TranslateRequest;
};

export type AiApiTranslateResponse = ({
    [key: string]: unknown;
});

export type DataGetSyncMetaRouteResponse = ({
    [key: string]: SyncMetaEntry;
});

export type DataListChannelsData = {
    includeStats?: boolean;
};

export type DataListChannelsResponse = (Array<ChannelResponse>);

export type DataUpsertChannelData = {
    channelId: string;
    requestBody: ChannelUpsertRequest;
};

export type DataUpsertChannelResponse = (ChannelResponse);

export type DataDeleteChannelData = {
    channelId: string;
};

export type DataDeleteChannelResponse = (StatusResponse);

export type DataStartBulkFollowData = {
    requestBody: BulkFollowRequest;
};

export type DataStartBulkFollowResponse = (BulkFollowStartResponse);

export type DataGetBulkFollowStatusData = {
    followJobId: string;
};

export type DataGetBulkFollowStatusResponse = (BulkFollowJobStatusResponse);

export type DataBulkFollowEventsData = {
    followJobId: string;
};

export type DataBulkFollowEventsResponse = (unknown);

export type DataCancelBulkFollowData = {
    followJobId: string;
};

export type DataCancelBulkFollowResponse = (CancelBulkFollowResponse);

export type DataBulkReresolveStartIdsEndpointData = {
    requestBody?: BulkReresolveStartIdsRequest;
};

export type DataBulkReresolveStartIdsEndpointResponse = (BulkReresolveStartIdsResponse);

export type DataBulkResetSyncEndpointData = {
    requestBody: BulkResetSyncRequest;
};

export type DataBulkResetSyncEndpointResponse = (BulkResetSyncResponse);

export type DataBulkSyncSettingsEndpointData = {
    requestBody: BulkSyncSettingsRequest;
};

export type DataBulkSyncSettingsEndpointResponse = (BulkUpdatedResponse);

export type DataListSettingGroupsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataCreateSettingGroupData = {
    requestBody: SettingGroupWriteRequest;
};

export type DataCreateSettingGroupResponse = ({
    [key: string]: unknown;
});

export type DataUpdateSettingGroupData = {
    groupId: string;
    requestBody: SettingGroupWriteRequest;
};

export type DataUpdateSettingGroupResponse = ({
    [key: string]: unknown;
});

export type DataDeleteSettingGroupData = {
    groupId: string;
};

export type DataDeleteSettingGroupResponse = ({
    [key: string]: (string);
});

export type DataBulkAssignSettingGroupData = {
    requestBody: BulkChannelSettingGroupRequest;
};

export type DataBulkAssignSettingGroupResponse = (BulkSettingGroupResponse);

export type DataBulkChannelTagsEndpointData = {
    requestBody: BulkChannelTagsRequest;
};

export type DataBulkChannelTagsEndpointResponse = (BulkChannelTagsResponse);

export type DataGetChannelStatsData = {
    channelId: string;
};

export type DataGetChannelStatsResponse = (ChannelStatsResponse);

export type DataListPostsData = {
    requestBody: PostFeedRequest;
};

export type DataListPostsResponse = (Array<PostResponse>);

export type DataDiscoverCandidatesData = {
    requestBody: DiscoverCandidatesRequest;
};

export type DataDiscoverCandidatesResponse = (DiscoverCandidatesResponse);

export type DataListDiscoverIgnoredResponse = (Array<IgnoredChannelResponse>);

export type DataAddDiscoverIgnoredData = {
    requestBody: DiscoverIgnoreRequest;
};

export type DataAddDiscoverIgnoredResponse = (DiscoverIgnoredAddedResponse);

export type DataRemoveDiscoverIgnoredData = {
    requestBody: DiscoverIgnoreRequest;
};

export type DataRemoveDiscoverIgnoredResponse = (DiscoverIgnoredRemovedResponse);

export type DataListDiscoverProbesData = {
    limit?: number;
    offset?: number;
    status?: (string | null);
};

export type DataListDiscoverProbesResponse = (Array<HandleProbeResponse>);

export type DataGetDiscoverProbeQueueResponse = (DiscoverProbeQueueResponse);

export type DataRecheckDiscoverProbesData = {
    requestBody: DiscoverProbeRequest;
};

export type DataRecheckDiscoverProbesResponse = (DiscoverProbeRecheckResponse);

export type DataCreateDiscoverReportData = {
    requestBody: DiscoverCandidatesRequest;
};

export type DataCreateDiscoverReportResponse = (DiscoverReportResponse);

export type DataListDiscoverReportsData = {
    limit?: number;
    offset?: number;
    search?: (string | null);
};

export type DataListDiscoverReportsResponse = (Array<DiscoverReportListItemResponse>);

export type DataGetLatestDiscoverReportResponse = ((DiscoverReportResponse | null));

export type DataGetDiscoverReportData = {
    reportId: string;
};

export type DataGetDiscoverReportResponse = (DiscoverReportResponse);

export type DataDeleteDiscoverReportData = {
    reportId: string;
};

export type DataDeleteDiscoverReportResponse = (StatusResponse);

export type DataPostsCountsData = {
    requestBody: PostScopeRequest;
};

export type DataPostsCountsResponse = ({
    [key: string]: (number);
});

export type DataLookupPostsRouteData = {
    requestBody: PostLookupRequest;
};

export type DataLookupPostsRouteResponse = (Array<PostResponse>);

export type DataBulkUpsertPostsRouteData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataBulkUpsertPostsRouteResponse = (BulkUpsertPostsResponse);

export type DataListSummariesData = {
    limit?: number;
    offset?: number;
    search?: (string | null);
};

export type DataListSummariesResponse = (Array<SummaryListItemResponse>);

export type DataGetSummaryData = {
    summaryId: string;
};

export type DataGetSummaryResponse = (SummaryResponse);

export type DataUpsertSummaryData = {
    requestBody: SummaryUpsertRequest;
    summaryId: string;
};

export type DataUpsertSummaryResponse = (SummaryResponse);

export type DataDeleteSummaryData = {
    summaryId: string;
};

export type DataDeleteSummaryResponse = (StatusResponse);

export type DataListTagRunsData = {
    limit?: number;
    offset?: number;
};

export type DataListTagRunsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataGetTagRunData = {
    tagRunId: string;
};

export type DataGetTagRunResponse = ({
    [key: string]: unknown;
});

export type DataUpsertTagRunData = {
    requestBody: {
        [key: string]: unknown;
    };
    tagRunId: string;
};

export type DataUpsertTagRunResponse = ({
    [key: string]: unknown;
});

export type DataDeleteTagRunData = {
    tagRunId: string;
};

export type DataDeleteTagRunResponse = ({
    [key: string]: (string);
});

export type DataListBotCredentialsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertBotCredentialData = {
    botId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataUpsertBotCredentialResponse = ({
    [key: string]: unknown;
});

export type DataDeleteBotCredentialData = {
    botId: string;
};

export type DataDeleteBotCredentialResponse = ({
    [key: string]: (string);
});

export type DataMigrateBotCredentialsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataMigrateBotCredentialsResponse = ({
    [key: string]: unknown;
});

export type DataListChatDestinationsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertChatDestinationData = {
    destId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataUpsertChatDestinationResponse = ({
    [key: string]: unknown;
});

export type DataDeleteChatDestinationData = {
    destId: string;
};

export type DataDeleteChatDestinationResponse = ({
    [key: string]: (string);
});

export type DataUpsertEmbeddingsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataUpsertEmbeddingsResponse = ({
    [key: string]: (number);
});

export type DataGetTranslationData = {
    channelName: string;
    language: string;
    postId: number;
};

export type DataGetTranslationResponse = (({
    [key: string]: unknown;
} | null));

export type DataListTranslationsData = {
    limit?: number;
    offset?: number;
};

export type DataListTranslationsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertTranslationsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataUpsertTranslationsResponse = ({
    [key: string]: (number);
});

export type DataListPublishLogsRouteData = {
    limit?: number;
    offset?: number;
};

export type DataListPublishLogsRouteResponse = (Array<PublishLogResponse>);

export type DataCreatePublishLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreatePublishLogsResponse = (LogWriteResponse);

export type DataListSyncLogsRouteData = {
    limit?: number;
    offset?: number;
};

export type DataListSyncLogsRouteResponse = (Array<SyncLogResponse>);

export type DataCreateSyncLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateSyncLogsResponse = (LogWriteResponse);

export type DataListLlmLogsRouteData = {
    limit?: number;
    offset?: number;
};

export type DataListLlmLogsRouteResponse = (Array<LLMLogResponse>);

export type DataCreateLlmLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateLlmLogsResponse = (LogWriteResponse);

export type DataListEmbeddingLogsRouteData = {
    limit?: number;
    offset?: number;
};

export type DataListEmbeddingLogsRouteResponse = (Array<EmbeddingLogResponse>);

export type DataCreateEmbeddingLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateEmbeddingLogsResponse = (LogWriteResponse);

export type DataListNetworkLogsRouteData = {
    limit?: number;
    offset?: number;
};

export type DataListNetworkLogsRouteResponse = (Array<NetworkLogResponse>);

export type DataCreateNetworkLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateNetworkLogsResponse = (LogWriteResponse);

export type DataDbStatsResponse = (DbStatsResponse);

export type DataTableSizesResponse = (Array<TableSizeResponse>);

export type DataClearTableRouteData = {
    name: string;
};

export type DataClearTableRouteResponse = (ClearTableResponse);

export type DataPurgeLogsData = {
    clearAll?: boolean;
    logId?: (string | null);
    olderThanDays?: (number | null);
    type?: (string | null);
};

export type DataPurgeLogsResponse = (PurgeLogsResponse);

export type DataGetNetworkSettingsResponse = ({
    [key: string]: unknown;
});

export type DataPutNetworkSettingsData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataPutNetworkSettingsResponse = ({
    [key: string]: unknown;
});

export type DataGetSettingData = {
    key: string;
};

export type DataGetSettingResponse = ({
    [key: string]: unknown;
});

export type DataPutSettingData = {
    key: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataPutSettingResponse = ({
    [key: string]: unknown;
});

export type DataImportDataData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataImportDataResponse = ({
    [key: string]: unknown;
});

export type DataExportDataResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobsJobsStatusResponse = ({
    [key: string]: unknown;
});

export type JobsGetRuntimeConfigResponse = (RuntimeConfigResponse);

export type JobsTriggerSchedulerJobData = {
    jobId: string;
};

export type JobsTriggerSchedulerJobResponse = ({
    [key: string]: unknown;
});

export type JobsUpdateSchedulerJobData = {
    jobId: string;
    requestBody: UpdateJobRequest;
};

export type JobsUpdateSchedulerJobResponse = ({
    [key: string]: unknown;
});

export type JobsStartSyncJobData = {
    requestBody: StartSyncJobRequest;
};

export type JobsStartSyncJobResponse = (StartSyncJobResponse);

export type JobsGetSyncJobStatusData = {
    jobId: string;
};

export type JobsGetSyncJobStatusResponse = (SyncJobStatusResponse);

export type JobsSyncJobEventsData = {
    jobId: string;
};

export type JobsSyncJobEventsResponse = (unknown);

export type JobsCancelSyncJobData = {
    jobId: string;
};

export type JobsCancelSyncJobResponse = (CancelSyncJobResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NetworkApiTestProxyData = {
    requestBody: TestProxyRequest;
};

export type NetworkApiTestProxyResponse = ({
    [key: string]: unknown;
});

export type NetworkApiProxyHealthResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorStatusResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorIpResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorRestartResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorNewIdentityData = {
    requestBody: TorNewIdentityRequest;
};

export type NetworkApiTorNewIdentityResponse = ({
    [key: string]: unknown;
});

export type RagRagStatusResponse = ({
    [key: string]: unknown;
});

export type RagRagEmbedData = {
    requestBody: RagEmbedRequest;
};

export type RagRagEmbedResponse = ({
    [key: string]: unknown;
});

export type RagRagSearchData = {
    requestBody: RagSearchRequest;
};

export type RagRagSearchResponse = ({
    [key: string]: unknown;
});

export type TelegramApiScrapeData = {
    requestBody: ScrapeRequest;
};

export type TelegramApiScrapeResponse = ({
    [key: string]: unknown;
});

export type TelegramApiChannelInfoData = {
    requestBody: ChannelInfoRequest;
};

export type TelegramApiChannelInfoResponse = ({
    [key: string]: unknown;
});

export type TelegramApiResolveStartTimeData = {
    requestBody: ResolveStartTimeRequest;
};

export type TelegramApiResolveStartTimeResponse = ({
    [key: string]: unknown;
});

export type TelegramApiBotInfoData = {
    requestBody: BotInfoRequest;
};

export type TelegramApiBotInfoResponse = ({
    [key: string]: unknown;
});

export type TelegramApiPublishData = {
    requestBody: PublishRequest;
};

export type TelegramApiPublishResponse = ({
    [key: string]: unknown;
});

export type TelegramApiChannelPhotoData = {
    channelId: string;
};

export type TelegramApiChannelPhotoResponse = (unknown);

export type TelegramApiPostThumbData = {
    channelName: string;
    postId: number;
};

export type TelegramApiPostThumbResponse = (unknown);

export type TelegramApiBotFileData = {
    credentialId: string;
    path: string;
};

export type TelegramApiBotFileResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);