// This file is auto-generated by @hey-api/openapi-ts

export type ActiveSyncJobSummary = {
    jobId: string;
    status: string;
    source: string;
    channelCount: number;
    runningChannels: number;
    pendingChannels: number;
    allowedConcurrency: number;
    concurrencyInUse: number;
    effectiveProxyCapacity?: (number | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BotInfoRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    credentialId?: (string | null);
    token?: (string | null);
    method: string;
    params?: ({
    [key: string]: unknown;
} | null);
};

export type BulkChannelTagsRequest = {
    updates: Array<BulkChannelTagUpdate>;
};

export type BulkChannelTagUpdate = {
    channelId: string;
    tags: Array<{
        [key: string]: unknown;
    }>;
};

export type BulkReresolveStartIdsRequest = {
    dryRun?: boolean;
    limit?: (number | null);
    channelIds?: (Array<(string)> | null);
    autoFollowOnly?: boolean;
};

export type BulkResetSyncRequest = {
    confirm?: boolean;
    channelIds?: (Array<(string)> | null);
    autoFollowOnly?: boolean;
};

export type BulkSyncSettingsRequest = {
    channelIds?: (Array<(string)> | null);
    regularSyncEnabled?: (boolean | null);
    dynamicSyncEnabled?: (boolean | null);
    autoSyncIntervalMinutes?: (number | null);
    dynamicSyncExpectedPosts?: (number | null);
};

export type CancelSyncJobResponse = {
    jobId: string;
    status: string;
};

export type ChannelInfoRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    channelName: string;
};

export type ChannelSyncProgress = {
    channelId: string;
    channelName: string;
    status: string;
    postsFetched?: number;
    newLatestId?: (number | null);
    error?: (string | null);
};

export type ChatMessage = {
    role: string;
    text: string;
};

export type ChatRequest = {
    channels?: Array<(string)>;
    channelsText?: string;
    postsText?: string;
    language?: string;
    model?: (string | null);
    temperature?: number;
    message: string;
    history?: Array<ChatMessage>;
    ragMode?: boolean;
    provider?: string;
};

export type EmbedRequest = {
    texts: Array<(string)>;
    model?: (string | null);
    provider?: string;
};

export type GlobalStartTimeSnapshot = {
    mode: string;
    value?: (string | number | null);
    effectiveMs: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobIntervals = {
    autoSyncCheckSeconds: number;
    embeddingsSeconds: number;
    autoSummarySeconds: number;
    retentionHours: number;
    translationBatchSeconds: number;
};

export type JobsRuntimeSettings = {
    enabled: {
        [key: string]: (boolean);
    };
    intervals: JobIntervals;
};

export type Message = {
    message: string;
};

export type NetworkRuntimeSettings = {
    proxyEnabled?: boolean;
    proxyUrls?: Array<(string)>;
    proxyDefaultConcurrency?: number;
    proxyConcurrencyOverrides?: {
        [key: string]: (number);
    };
    effectiveProxyCapacity?: number;
    proxyLanes?: Array<ProxyLaneSnapshot>;
    torEnabled?: boolean;
    torMode?: (string | null);
    torProxyUrls?: (string | null);
    torRotationStrategy?: (string | null);
    torControlEnabled?: boolean;
    torControlPort?: (number | null);
    torAutoRotate?: boolean;
    torRotationThreshold: number;
    envFallbackConfigured: boolean;
    usingEnvFallback: boolean;
    torAvailable: boolean;
    torSocksProxy: string;
    effectiveTorEnabled: boolean;
    resolvedProxyCount: number;
    resolvedProxies?: Array<(string)>;
    fetchTimeoutSeconds: number;
    fetchRetries: number;
    fetchInitialDelayMs: number;
    proxyCooldownMs: number;
    telegramApiRetries: number;
    telegramApiInitialDelayMs: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ProxyLaneSnapshot = {
    proxyUrl: string;
    maxParallel: number;
    inUse: number;
    inCooldown: boolean;
};

export type PublishRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    credentialId?: (string | null);
    token?: (string | null);
    chatId: string;
    text: string;
    metadataText?: (string | null);
};

export type RagEmbedRequest = {
    limit?: number;
};

export type RagSearchRequest = {
    query: string;
    channels?: (Array<(string)> | null);
    startDate?: (number | null);
    endDate?: (number | null);
    limit?: number;
    scanLimit?: number;
};

export type ResolveStartTimeRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    channelName: string;
    targetTimeMs: number;
};

export type RetentionRuntimeSettings = {
    postRetentionDays: number;
    logRetentionDays: number;
};

export type RuntimeConfigResponse = {
    nowMs: number;
    scrapeCutoffMs: number;
    effectiveGlobalStartTimeMs: number;
    globalStartTime: GlobalStartTimeSnapshot;
    sync: SyncRuntimeSettings;
    scraper: ScraperRuntimeSettings;
    network: NetworkRuntimeSettings;
    jobs: JobsRuntimeSettings;
    retention: RetentionRuntimeSettings;
    constants: RuntimeConstants;
    activeSyncJob?: (ActiveSyncJobSummary | null);
};

export type RuntimeConstants = {
    syncMaxRetries: number;
    syncRetryBackoffBaseMs: number;
    syncJobSseThrottleMs: number;
    syncJobPersistIntervalMs: number;
    autoSyncPauseDurationMs: number;
    autoSyncFailureThresholdMin: number;
    embeddingsChunkSize: number;
    embeddingsBackfillLimitDefault: number;
    translationBatchLimit: number;
    translationBatchMaxChars: number;
    environment: string;
};

export type ScrapeRequest = {
    proxyEnabled?: boolean;
    proxies?: (Array<(string)> | null);
    torAutoRotate?: boolean;
    torRotationThreshold?: number;
    url: string;
    knownLatestId?: (number | null);
    knownDisplayName?: (string | null);
    knownPhotoUrl?: (string | null);
};

export type ScraperRuntimeSettings = {
    maxPostsPerChannel: number;
    iterationLimit: number;
};

export type StartSyncJobRequest = {
    channelIds?: (Array<(string)> | null);
    source?: string;
};

export type StartSyncJobResponse = {
    jobId: string;
};

export type SummaryRequest = {
    channels: Array<(string)>;
    channelsText?: string;
    postsText: string;
    language?: string;
    model?: (string | null);
    temperature?: number;
    provider?: string;
};

export type SyncJobStatusResponse = {
    jobId: string;
    status: string;
    source: string;
    channels: Array<ChannelSyncProgress>;
    createdAt: number;
    finishedAt?: (number | null);
};

export type SyncRuntimeSettings = {
    regularSyncIntervalMinutes: number;
    dynamicSyncEnabledDefault: boolean;
    dynamicSyncExpectedPostsDefault: number;
    syncFailureBackoffMinutes: number;
    syncConcurrency: number;
    consecutiveFailures: number;
    autoSyncPauseUntil?: (number | null);
    globalStartTimeMode?: (string | null);
    globalStartTimeValue?: (string | number | null);
};

export type TagRequest = {
    channels: Array<(string)>;
    channelsText?: string;
    postsText: string;
    allTags?: string;
    tagMode?: string;
    model?: (string | null);
    temperature?: number;
    provider?: string;
    tagsPerChannelMin?: (number | null);
    tagsPerChannelMax?: (number | null);
};

export type TestProxyRequest = {
    proxyUrl: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TorNewIdentityRequest = {
    port?: (number | null);
};

export type TranslateRequest = {
    posts: Array<{
        [key: string]: (string);
    }>;
    targetLanguage: string;
    model?: (string | null);
    provider?: string;
};

export type UpdateJobRequest = {
    enabled: boolean;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AiApiListModelsResponse = ({
    [key: string]: unknown;
});

export type AiApiSummaryData = {
    requestBody: SummaryRequest;
};

export type AiApiSummaryResponse = ({
    [key: string]: unknown;
});

export type AiApiSummaryPromptData = {
    requestBody: SummaryRequest;
};

export type AiApiSummaryPromptResponse = ({
    [key: string]: unknown;
});

export type AiApiSummaryStreamData = {
    requestBody: SummaryRequest;
};

export type AiApiSummaryStreamResponse = (unknown);

export type AiApiChatStreamData = {
    requestBody: ChatRequest;
};

export type AiApiChatStreamResponse = (unknown);

export type AiApiTagPromptData = {
    requestBody: TagRequest;
};

export type AiApiTagPromptResponse = ({
    [key: string]: (string);
});

export type AiApiTagStreamData = {
    requestBody: TagRequest;
};

export type AiApiTagStreamResponse = (unknown);

export type AiApiEmbeddingsData = {
    requestBody: EmbedRequest;
};

export type AiApiEmbeddingsResponse = ({
    [key: string]: unknown;
});

export type AiApiTranslateData = {
    requestBody: TranslateRequest;
};

export type AiApiTranslateResponse = ({
    [key: string]: unknown;
});

export type DataGetSyncMetaRouteResponse = ({
    [key: string]: unknown;
});

export type DataListChannelsData = {
    includeStats?: boolean;
};

export type DataListChannelsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertChannelData = {
    channelId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataUpsertChannelResponse = ({
    [key: string]: unknown;
});

export type DataDeleteChannelData = {
    channelId: string;
};

export type DataDeleteChannelResponse = ({
    [key: string]: (string);
});

export type DataBulkReresolveStartIdsEndpointData = {
    requestBody?: BulkReresolveStartIdsRequest;
};

export type DataBulkReresolveStartIdsEndpointResponse = ({
    [key: string]: unknown;
});

export type DataBulkResetSyncEndpointData = {
    requestBody: BulkResetSyncRequest;
};

export type DataBulkResetSyncEndpointResponse = ({
    [key: string]: unknown;
});

export type DataBulkSyncSettingsEndpointData = {
    requestBody: BulkSyncSettingsRequest;
};

export type DataBulkSyncSettingsEndpointResponse = ({
    [key: string]: (number);
});

export type DataBulkChannelTagsEndpointData = {
    requestBody: BulkChannelTagsRequest;
};

export type DataBulkChannelTagsEndpointResponse = ({
    [key: string]: unknown;
});

export type DataGetChannelStatsData = {
    channelId: string;
};

export type DataGetChannelStatsResponse = ({
    [key: string]: unknown;
});

export type DataListPostsData = {
    channelName?: (string | null);
    channelNames?: (string | null);
    endDate?: (number | null);
    startDate?: (number | null);
};

export type DataListPostsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataBulkUpsertPostsRouteData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataBulkUpsertPostsRouteResponse = ({
    [key: string]: (number);
});

export type DataListSummariesResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertSummaryData = {
    requestBody: {
        [key: string]: unknown;
    };
    summaryId: string;
};

export type DataUpsertSummaryResponse = ({
    [key: string]: unknown;
});

export type DataDeleteSummaryData = {
    summaryId: string;
};

export type DataDeleteSummaryResponse = ({
    [key: string]: (string);
});

export type DataListTagRunsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertTagRunData = {
    requestBody: {
        [key: string]: unknown;
    };
    tagRunId: string;
};

export type DataUpsertTagRunResponse = ({
    [key: string]: unknown;
});

export type DataDeleteTagRunData = {
    tagRunId: string;
};

export type DataDeleteTagRunResponse = ({
    [key: string]: (string);
});

export type DataListBotCredentialsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertBotCredentialData = {
    botId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataUpsertBotCredentialResponse = ({
    [key: string]: unknown;
});

export type DataDeleteBotCredentialData = {
    botId: string;
};

export type DataDeleteBotCredentialResponse = ({
    [key: string]: (string);
});

export type DataMigrateBotCredentialsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataMigrateBotCredentialsResponse = ({
    [key: string]: unknown;
});

export type DataListChatDestinationsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertChatDestinationData = {
    destId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataUpsertChatDestinationResponse = ({
    [key: string]: unknown;
});

export type DataDeleteChatDestinationData = {
    destId: string;
};

export type DataDeleteChatDestinationResponse = ({
    [key: string]: (string);
});

export type DataListEmbeddingsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertEmbeddingsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataUpsertEmbeddingsResponse = ({
    [key: string]: (number);
});

export type DataListTranslationsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataUpsertTranslationsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataUpsertTranslationsResponse = ({
    [key: string]: (number);
});

export type DataListPublishLogsRouteResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataCreatePublishLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreatePublishLogsResponse = ({
    [key: string]: (number);
});

export type DataListSyncLogsRouteResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataCreateSyncLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateSyncLogsResponse = ({
    [key: string]: (number);
});

export type DataListLlmLogsRouteResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataCreateLlmLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateLlmLogsResponse = ({
    [key: string]: (number);
});

export type DataListEmbeddingLogsRouteResponse = (({
    [key: string]: unknown;
} | Array<{
    [key: string]: unknown;
}>));

export type DataCreateEmbeddingLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateEmbeddingLogsResponse = ({
    [key: string]: (number);
});

export type DataListNetworkLogsRouteResponse = (Array<{
    [key: string]: unknown;
}>);

export type DataCreateNetworkLogsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type DataCreateNetworkLogsResponse = ({
    [key: string]: (number);
});

export type DataDbStatsResponse = ({
    [key: string]: unknown;
});

export type DataPurgeLogsData = {
    clearAll?: boolean;
    logId?: (string | null);
    olderThanDays?: (number | null);
    type?: (string | null);
};

export type DataPurgeLogsResponse = ({
    [key: string]: unknown;
});

export type DataGetNetworkSettingsResponse = ({
    [key: string]: unknown;
});

export type DataPutNetworkSettingsData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataPutNetworkSettingsResponse = ({
    [key: string]: unknown;
});

export type DataGetSettingData = {
    key: string;
};

export type DataGetSettingResponse = ({
    [key: string]: unknown;
});

export type DataPutSettingData = {
    key: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataPutSettingResponse = ({
    [key: string]: unknown;
});

export type DataImportDataData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type DataImportDataResponse = ({
    [key: string]: unknown;
});

export type DataExportDataResponse = ({
    [key: string]: unknown;
});

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobsJobsStatusResponse = ({
    [key: string]: unknown;
});

export type JobsGetRuntimeConfigResponse = (RuntimeConfigResponse);

export type JobsTriggerSchedulerJobData = {
    jobId: string;
};

export type JobsTriggerSchedulerJobResponse = ({
    [key: string]: unknown;
});

export type JobsUpdateSchedulerJobData = {
    jobId: string;
    requestBody: UpdateJobRequest;
};

export type JobsUpdateSchedulerJobResponse = ({
    [key: string]: unknown;
});

export type JobsStartSyncJobData = {
    requestBody: StartSyncJobRequest;
};

export type JobsStartSyncJobResponse = (StartSyncJobResponse);

export type JobsGetSyncJobStatusData = {
    jobId: string;
};

export type JobsGetSyncJobStatusResponse = (SyncJobStatusResponse);

export type JobsSyncJobEventsData = {
    jobId: string;
};

export type JobsSyncJobEventsResponse = (unknown);

export type JobsCancelSyncJobData = {
    jobId: string;
};

export type JobsCancelSyncJobResponse = (CancelSyncJobResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NetworkApiTestProxyData = {
    requestBody: TestProxyRequest;
};

export type NetworkApiTestProxyResponse = ({
    [key: string]: unknown;
});

export type NetworkApiProxyHealthResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorStatusResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorIpResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorRestartResponse = ({
    [key: string]: unknown;
});

export type NetworkApiTorNewIdentityData = {
    requestBody: TorNewIdentityRequest;
};

export type NetworkApiTorNewIdentityResponse = ({
    [key: string]: unknown;
});

export type RagRagStatusResponse = ({
    [key: string]: unknown;
});

export type RagRagEmbedData = {
    requestBody: RagEmbedRequest;
};

export type RagRagEmbedResponse = ({
    [key: string]: unknown;
});

export type RagRagSearchData = {
    requestBody: RagSearchRequest;
};

export type RagRagSearchResponse = ({
    [key: string]: unknown;
});

export type TelegramApiScrapeData = {
    requestBody: ScrapeRequest;
};

export type TelegramApiScrapeResponse = ({
    [key: string]: unknown;
});

export type TelegramApiChannelInfoData = {
    requestBody: ChannelInfoRequest;
};

export type TelegramApiChannelInfoResponse = ({
    [key: string]: unknown;
});

export type TelegramApiResolveStartTimeData = {
    requestBody: ResolveStartTimeRequest;
};

export type TelegramApiResolveStartTimeResponse = ({
    [key: string]: unknown;
});

export type TelegramApiBotInfoData = {
    requestBody: BotInfoRequest;
};

export type TelegramApiBotInfoResponse = ({
    [key: string]: unknown;
});

export type TelegramApiPublishData = {
    requestBody: PublishRequest;
};

export type TelegramApiPublishResponse = ({
    [key: string]: unknown;
});

export type TelegramApiChannelPhotoData = {
    channelId: string;
};

export type TelegramApiChannelPhotoResponse = (unknown);

export type TelegramApiPostThumbData = {
    channelName: string;
    postId: number;
};

export type TelegramApiPostThumbResponse = (unknown);

export type TelegramApiBotFileData = {
    credentialId: string;
    path: string;
};

export type TelegramApiBotFileResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);