"""An Account's own AI Keys (BYOK-01, ADR-016).

`tg_ai_credentials` is `tg_bot_credentials` again, for the same kind of object:
a secret somebody pasted in, stored encrypted so an unattended job can use it,
never shown back. The two are twins deliberately.

`user_id` is `NOT NULL` from the first row with a cascading key, which is what
puts this table on `CREATED_AFTER_THE_BACKFILL` rather than on ticket 34's
inventory: a row nobody owns has never been expressible here, so there is
nothing to stamp.

Hand-written rather than autogenerated. `--autogenerate` against this database
also proposes dropping seven hand-made partial indexes and relaxing four
`NOT NULL`s it cannot see in the models — drift that predates this ticket, and a
migration that carried it would be a schema change nobody reviewed riding along
with one somebody did.

Revision ID: e2f3a4b5c6d7
Revises: d1e2f3a4b5c6
Create Date: 2026-09-08

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision = "e2f3a4b5c6d7"
down_revision = "d1e2f3a4b5c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "tg_ai_credentials",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("key_encrypted", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_validated", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tg_ai_credentials_user_id"),
        "tg_ai_credentials",
        ["user_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_tg_ai_credentials_user_id"), table_name="tg_ai_credentials")
    op.drop_table("tg_ai_credentials")
