"""Quota ledger: Requests per User, per day, per Budget (ticket 08)

Creates `tg_quota_usage`. Nothing reads it to decide anything yet — ticket 23
reads it at enqueue to pick a lane, ticket 24 to refuse at the ceiling. The
migration is additive and carries no data move, so it is safe under the
unattended `alembic upgrade head` in `scripts/prestart.sh`.

Composite primary key `(user_id, day, budget)`, which is decision 19 of
`docs/multi-user-tenancy-plan.md` and the shape the question has: "what has this
User spent today, on this Budget" is then a primary-key hit rather than a scan.

`day` is a DATE. The reset is UTC midnight (decision 16), and a timestamp would
push that boundary out into every reader, where they would eventually disagree
about it.

`ix_tg_quota_usage_day` exists because the Admin view asks the other question —
everyone, on one day — and the primary key's leading column is `user_id`, so the
PK index cannot serve a predicate on `day` alone.

The autogenerated version of this file also carried a dozen unrelated
`drop_index` and `alter_column` statements, for indexes and column types declared
in raw SQL that autogenerate cannot see. That is drift in the *comparison*, not
in the database, and applying it would delete live indexes.

Revision ID: e9f0a1b2c3d4
Revises: d7e8f9a0b1c2
Create Date: 2026-08-25

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision = "e9f0a1b2c3d4"
down_revision = "d7e8f9a0b1c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "tg_quota_usage",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("budget", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "day", "budget"),
    )
    op.create_index(
        op.f("ix_tg_quota_usage_day"), "tg_quota_usage", ["day"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_tg_quota_usage_day"), table_name="tg_quota_usage")
    op.drop_table("tg_quota_usage")
