import type {
  BotCredentialResponse,
  ChannelStatsResponse,
  ChatDestinationResponse,
  DbStatsResponse,
  EmbeddingLogResponse,
  PostTranslationResponse,
  PublishLogResponse,
  SyncLogResponse,
  TagRunResponse,
} from "@/client"

/**
 * Domain types (B7).
 *
 * Nine of these are `<GeneratedResponse> & <what the frontend also knows>`.
 * The generated half is the server's contract and is regenerated by
 * `scripts/generate-client.sh`; **do not restate its fields here**. If the
 * server renames or drops one, this file stops compiling, which is the point.
 *
 * The local half is deliberate, not leftover. It carries four kinds of thing
 * the generated types cannot express:
 *
 * 1. **Fields carried through an open model's `extra`.** `ChannelResponse` and
 *    `SummaryResponse` allow extra keys, so the group-inherited channel fields
 *    and the summary UI flags arrive as `[key: string]: unknown` with their
 *    names erased. They are real wire fields; they are just not declared
 *    server-side, for the reasons in `app/schemas/channels.py`.
 * 2. **Nested shapes the backend leaves loose on purpose.** `TagRun.applyResult`
 *    and `Post.media` are untyped server-side because pinning them would make a
 *    prompt or storage change into a schema migration.
 * 3. **Client-side augmentations** the server never sends — `ChannelStats.latestId`
 *    is written locally after a sync.
 * 4. **Literal-union narrowing** — four log types know `status` is
 *    `"success" | "failed"`, where OpenAPI only says `string`.
 *
 * When adding a field, ask which half it belongs in. If the server sends it and
 * declares it, it is already here via the generated type and must not be
 * repeated.
 *
 * ## Why `Post`, `Channel`, `Summary`, `ChannelSettingGroup`, `LLMLog` and
 * ## `NetworkLog` are still hand-written
 *
 * Their generated counterparts are **open models**, which OpenAPI renders as a
 * top-level `[key: string]: unknown` index signature. Basing a type on one is
 * actively harmful downstream: `Omit<T, K>` over a type with an index signature
 * collapses every named property into the index signature, so
 * `SummaryListItem = Omit<Summary, …>` would degrade every field to `unknown`.
 * Rebasing all fifteen produced **190 type errors**, almost all of that shape.
 *
 * `tests/types-conform.test-d.ts` covers these instead: it asserts the server's
 * declared fields stay assignable to the hand-written ones, so drift still fails
 * the build without importing the index signature.
 */

export type PostMediaKind =
  | "photo"
  | "video"
  | "voice"
  | "audio"
  | "document"
  | "poll"
  | "sticker"
  | "link_preview"
  | "grouped"

export interface PostLinkPreview {
  title?: string
  description?: string
  siteName?: string
}

export interface PostPollMedia {
  question?: string
  options?: string[]
  [key: string]: unknown
}

/** One reaction chip. Mirrors the backend ReactionCount schema. */
export interface PostReactionCount {
  /** Absent for the paid-stars chip and for custom (premium) emoji. */
  emoji?: string | null
  customEmojiId?: string | null
  count: number
  isPaid?: boolean | null
}

/**
 * Mirrors backend PostMedia schema (camelCase API).
 *
 * A `type` rather than an `interface`, and that distinction is load-bearing:
 * TypeScript gives type aliases an implicit index signature but withholds one
 * from interfaces, so only the alias form is assignable to the server's
 * `media?: { [key: string]: unknown }`. `types.conform.ts` asserts exactly that
 * assignability (B7b) and cannot with an interface. Nothing extends or merges
 * into this declaration, so the two forms are otherwise identical here.
 */
export type PostMedia = {
  kinds: PostMediaKind[]
  caption?: string | null
  durationSec?: number | null
  thumbApiPath?: string | null
  /** Telegram's display string, e.g. "16.4M". Use viewsCount to compare. */
  views?: string | null
  viewsCount?: number | null
  /** Flattened display string; per-chip counts live in reactionCounts. */
  reactions?: string | null
  reactionCounts?: PostReactionCount[] | null
  reactionsCount?: number | null
  linkPreview?: PostLinkPreview | null
  poll?: PostPollMedia | null
  groupedCount?: number | null
  isMediaOnly?: boolean
}

/** A Telegram link found in a post body. Mirrors the backend `links` JSON column. */
export interface PostBodyLink {
  url: string
  channel?: string | null
}

/**
 * The post a post replies to. Mirrors the backend `reply_to` JSON column.
 * `text` is Telegram's truncated excerpt of the parent, not its full body.
 */
export interface PostReplyRef {
  channel?: string | null
  authorName?: string | null
  text?: string | null
  url?: string | null
}

export interface Post {
  id: number
  channelName: string
  text: string
  date: string
  timestamp: number
  media?: PostMedia | null
  links?: PostBodyLink[] | null
  replyToPostId?: number | null
  replyTo?: PostReplyRef | null
  forwardedFrom?: string
  forwardedFromName?: string
  isAnchor?: boolean
  retrievedAt?: number
  retrievalJobId?: string
  retrievalPass?: "initial" | "incremental"
  retrievalSource?: string
}

export interface PostEmbedding {
  id: string // e.g. `${channelName}_${postId}`
  channelName: string
  postId: number
  vector: number[]
  text: string
}

export type PostTranslation = PostTranslationResponse &
  AlwaysSent<PostTranslationResponse, "translatedText" | "timestamp">

export interface Channel {
  id: string
  name: string
  displayName?: string
  photoUrl?: string
  bio?: string
  subscribers?: string
  photos?: string
  videos?: string
  files?: string
  links?: string
  startId?: number
  startTime?: number
  tags?: ChannelTag[] | string[]
  lastUpdated?: number
  regularSyncEnabled?: boolean
  dynamicSyncEnabled?: boolean
  autoSyncIntervalMinutes?: number
  dynamicSyncExpectedPosts?: number
  nextRegularSyncAt?: number | null
  nextDynamicSyncAt?: number | null
  isFrozen?: boolean
  isUnavailableOnWebView?: boolean
  includeInSyncAll?: boolean
  includeInBulkSync?: boolean
  allowIndividualSync?: boolean
  resetSyncEnabled?: boolean
  autoFollowForwarded?: boolean
  language?: string
  followedAt?: number
  telegramChatId?: number
  discoveredVia?: {
    channelName: string
    postId: number
    timestamp: number
  }
  historyCompleteToCutoff?: boolean
  /** Backward sync has walked back to the channel's first post. */
  historyReachedChannelStart?: boolean
  anchorPostId?: number
  oldestStoredPostTimestamp?: number
  settingGroupId?: string
  settingGroupName?: string
}

export interface ChannelSettingGroup {
  id: string
  name: string
  isDefault: boolean
  isReserved?: boolean
  regularSyncEnabled: boolean
  dynamicSyncEnabled: boolean
  autoSyncIntervalMinutes: number
  dynamicSyncExpectedPosts: number
  autoFollowForwarded: boolean
  isFrozen: boolean
  isUnavailableOnWebView: boolean
  includeInSyncAll: boolean
  includeInBulkSync: boolean
  allowIndividualSync: boolean
  resetSyncEnabled: boolean
  channelCount?: number
  createdAt?: number
  updatedAt?: number
}

export type TagSource = "manual" | "ai"

export interface ChannelTag {
  name: string
  source: TagSource
  assignedAt: number
}

export type GlobalStartTimeMode = "relative" | "absolute" | "retention"
export type GlobalStartTimeValue = number | string | null

/**
 * A bot credential.
 *
 * Local half: `token` is **never returned by the server** — see
 * `app/schemas/credentials.py`, where the response model is closed precisely so
 * a token cannot leak. It is present only on a credential the client just
 * created, or one still held in the legacy local store pending migration.
 */
export type BotCredential = BotCredentialResponse & {
  /** Present only when creating or migrating; never returned by GET. */
  token?: string
}

export type ChatDestination = ChatDestinationResponse

export interface Summary {
  id: string
  text: string
  channels: string[]
  startDate: number
  endDate: number
  language: string
  model?: string
  postCount?: number
  timestamp: number
  chatMessages?: { role: "user" | "model"; text: string }[]
  autoRegenerate?: boolean
  autoPublish?: boolean
  publishBotId?: string
  publishChatId?: string
  note?: string
  sendMetadata?: boolean
  metadataText?: string
  isStarred?: boolean
  postSearch?: string
  semanticSearchQuery?: string
  semanticSearchRespectsTimeRange?: boolean
  semanticSearchRespectsChannels?: boolean
  citedPosts?: Record<string, Post>
  /** Provenance when summary was not generated in-app (persisted in server `extra`). */
  source?: "pasted"
  /** Awaiting external AI response after Copy Prompt (persisted in server `extra`). */
  status?: "pending"
  /** Full prompt text saved when user copies for external AI (persisted in server `extra`). */
  promptText?: string
}

/**
 * What `GET /data/summaries` returns: metadata only.
 *
 * The heavy fields are deliberately absent. Measured on staging, `promptText`
 * alone was ~94% of that endpoint's payload (33 MB across 31 summaries), and
 * the list surfaces only ever rendered a message count and a short preview —
 * so `chatMessageCount` and `promptExcerpt` stand in for them.
 *
 * This is a separate type rather than `Summary` with the fields left undefined
 * so the compiler flags anything that needs the full row via `getSummary`.
 */
export type SummaryListItem = Omit<
  Summary,
  "citedPosts" | "promptText" | "chatMessages"
> & {
  chatMessageCount: number
  promptExcerpt?: string
}

export type PublishLog = Omit<PublishLogResponse, "status"> & {
  status: "success" | "failed"
} & AlwaysSent<PublishLogResponse, "timestamp">

export type SyncLog = Omit<SyncLogResponse, "status"> & {
  status: "success" | "failed"
} & AlwaysSent<SyncLogResponse, "timestamp" | "postsCount">

/**
 * What `GET /data/logs/{type}` actually returns — the corpus-sized fields are
 * only on the detail route now.
 *
 * `GET /data/logs/sync` was **56.28 MB for a page of 500 rows, 99.7% of it
 * request/response bodies**, and the viewer renders none of them until a row is
 * expanded. These `Omit`s are what stops a card reading a field the list never
 * sent; the full type is still what `useLogDetailQuery` returns.
 */
export type SyncLogListItem = Omit<SyncLog, "fullRequest" | "fullResponse">

/** See `SyncLogListItem`. */
export type PublishLogListItem = Omit<
  PublishLog,
  "fullRequest" | "fullResponse" | "textSent"
>

export interface LLMLog {
  id: string
  model: string
  prompt: string
  response: string
  systemInstruction?: string
  modelConfig?: any
  fullRequest?: any
  fullResponse?: any
  tokens?: number
  duration?: number
  status: "success" | "failed"
  error?: string
  timestamp: number
  type: "summary" | "chat" | "analysis" | "rag_chat"
}

/** See `SyncLogListItem`. `modelConfig` stays — it is `{temperature}`. */
export type LLMLogListItem = Omit<
  LLMLog,
  "prompt" | "response" | "systemInstruction" | "fullRequest" | "fullResponse"
>

export type EmbeddingLog = Omit<EmbeddingLogResponse, "status"> & {
  status: "success" | "failed"
} & AlwaysSent<EmbeddingLogResponse, "timestamp" | "textCount" | "duration">

export interface NetworkLog {
  id: string
  url: string
  method: string
  status: "success" | "failed"
  statusCode?: number
  error?: string
  duration: number
  timestamp: number
  source: string
  proxyUsed?: string
  attempts?: number
  telemetry?: any
}

/**
 * Per-channel post statistics.
 *
 * Local half: `latestId` is **not** a server field. The client writes it after a
 * sync reports a new latest id, so the progress bar can show `maxId / latestId`
 * without a second round trip.
 */

/**
 * Fields that a Pydantic default makes *look* optional in OpenAPI.
 *
 * `timestamp: int = 0` is not required in the schema, so the generated type says
 * `timestamp?: number` — but a response always serialises it. Re-requiring them
 * here is not overriding the server; it is restoring what the schema cannot say.
 */
type AlwaysSent<T, K extends keyof T> = Required<Pick<T, K>>

export type ChannelStats = ChannelStatsResponse & {
  latestId?: number
}

export interface SyncQueueItem {
  queueId: string
  channel: Channel
  source: string
  timestamp: number
  onComplete?: () => void
}

/**
 * Database statistics.
 *
 * Local half: the storage figures come from the browser's Storage API and the
 * IndexedDB mirror, not from the server. **A4 deletes them** along with the
 * IndexedDB layer; until then they are explicitly marked as client-side.
 */
/**
 * Row counts from the server, and nothing else.
 *
 * A4 removed the five client-only fields (`usage`, `quota`, `storeSizes`,
 * `storageEstimate`, `usageDetails`) along with the IndexedDB mirror and the
 * browser Storage API readings that fed them. This is now exactly the server's
 * response — no local half to merge in, which is why `getDBStats`'s
 * field-by-field `remote.x ?? local.x` merge could go too.
 */
export type DBStats = DbStatsResponse

/**
 * What `GET /data/tag-runs` returns: metadata only.
 *
 * The heavy fields are deliberately absent — `promptText` holds a full
 * serialized post corpus, so listing runs with it attached re-downloaded every
 * historical prompt. Fetch a single run to get them.
 */
export type TagRunSummary = Omit<
  TagRun,
  "promptText" | "responseText" | "allTagsSnapshot" | "suggestions"
>

/**
 * A tagging run.
 *
 * Local half: the four JSON payloads are `unknown` server-side on purpose —
 * their shape is set by the tagging prompt's output contract, which is versioned
 * by the prompt rather than by the schema (`app/schemas/tag_runs.py`).
 */
export type TagRun = AlwaysSent<
  TagRunResponse,
  "createdAt" | "updatedAt" | "channels" | "startDate" | "endDate" | "postCount"
> &
  Omit<
    TagRunResponse,
    | "status"
    | "source"
    | "mode"
    | "allTagsSnapshot"
    | "channelContextOptions"
    | "suggestions"
    | "applyResult"
  > & {
    status: "pending" | "completed" | "failed"
    source: "generated" | "pasted"
    mode: "add" | "remove"
    allTagsSnapshot?: string[]
    channelContextOptions?: {
      includeBio: boolean
      includeTags: boolean
    }
    suggestions?: Record<string, string[]>
    applyResult?: {
      channelsUpdated: number
      tagsAdded: number
      tagsRemoved: number
    }
  }

export type TabType =
  | "summary"
  | "posts"
  | "channels"
  | "tag"
  | "discover"
  | "history"
  | "db"
  | "chat"
  | "bots"
  | "settings"
  | "logs"

export interface ChatMessage {
  role: "user" | "model"
  text: string
  sources?: Post[]
}
