import { describe, expect, it } from "bun:test"
import { readdirSync, readFileSync, statSync } from "node:fs"
import { join } from "node:path"
import { logger } from "./logger"

const SRC = join(import.meta.dir, "..")
/** The one file allowed to wrap — and to talk about — the console. */
const LOGGER = join("lib", "logger.ts")

function sourceFiles(dir: string): string[] {
  const found: string[] = []
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) {
      // `client/` is generated by openapi-ts and not ours to police.
      if (entry === "node_modules" || entry === "client") continue
      found.push(...sourceFiles(path))
    } else if (
      (entry.endsWith(".ts") || entry.endsWith(".tsx")) &&
      !entry.includes(".test.")
    ) {
      found.push(path)
    }
  }
  return found
}

describe("logger", () => {
  it("is silent for debug outside dev", () => {
    // Unit tests run outside Vite, so `import.meta.env.DEV` is falsy — the same
    // branch a production build takes.
    const calls: unknown[][] = []
    const original = console.debug
    console.debug = (...args: unknown[]) => calls.push(args)
    try {
      logger.debug("[DB] Initializing database...")
    } finally {
      console.debug = original
    }
    expect(calls).toEqual([])
  })

  it("always reports warnings and errors", () => {
    const warns: unknown[][] = []
    const errors: unknown[][] = []
    const originalWarn = console.warn
    const originalError = console.error
    console.warn = (...args: unknown[]) => warns.push(args)
    console.error = (...args: unknown[]) => errors.push(args)
    try {
      logger.warn("degraded")
      logger.error("failed")
    } finally {
      console.warn = originalWarn
      console.error = originalError
    }
    expect(warns).toEqual([["degraded"]])
    expect(errors).toEqual([["failed"]])
  })
})

describe("shipped console output", () => {
  /**
   * B4: `[DB] …` narration was appearing in the console of a built, minified
   * bundle. `console.log` is unconditional, so it must not appear in shipped
   * source at all — use `logger.debug`, which folds away outside dev.
   */
  it("has no console.log left in application source", () => {
    const offenders: string[] = []
    for (const file of sourceFiles(SRC)) {
      if (file.endsWith(LOGGER)) continue
      if (readFileSync(file, "utf8").includes("console.log")) {
        offenders.push(file.slice(SRC.length + 1))
      }
    }
    expect(offenders).toEqual([])
  })

  it("routes console.debug only through the logger", () => {
    const offenders: string[] = []
    for (const file of sourceFiles(SRC)) {
      if (file.endsWith(LOGGER)) continue
      if (readFileSync(file, "utf8").includes("console.debug")) {
        offenders.push(file.slice(SRC.length + 1))
      }
    }
    expect(offenders).toEqual([])
  })

  it("scans a meaningful number of files", () => {
    // Guards against a path bug turning the sweeps above into no-ops.
    expect(sourceFiles(SRC).length).toBeGreaterThan(100)
  })
})
